import {create} from 'zustand';
import {BASE,CARDS,type Card,type Context,type Era,type Result,advanceRequirements,eligible,knowledge,points,reaction,restoreCard} from './engine.ts';
import {HELPERS,MILESTONES,researchPlan,type ResearchPlan} from './research.ts';
export type Entry={a:string;b:string;aId:string;bId:string;result:Result;time:number};
export type State={feedback:{id:number;kind:"success"|"fail";points:number}|null;researchCredits:number;roundCredits:number;researchProgress:number;researchGoal:string;researchResult:ResearchPlan|null;helperId:string|null;helperEnabled:boolean;helperNextAt:number;favorites:string[];milestones:string[];lastMilestone:string|null;study:()=>void;setResearchGoal:(goal:string)=>void;loadPair:(ids:[string,string])=>void;hireHelper:()=>void;toggleHelper:()=>void;helperTick:(now?:number)=>void;toggleFavorite:(id:string)=>void;cards:Card[];journal:Entry[];slots:(Card|null)[];last:Result|null;message:string;mode:'sandbox'|'challenge';scope:'stone'|'journey';era:Era;event:string;deadline:number;round:number;score:number;roundIds:string[];discovered:string[];done:boolean;hydrated:boolean;add:(c:Card,index?:number)=>void;clear:()=>void;craft:()=>void;start:(mode:'sandbox'|'challenge')=>void;next:()=>void;hydrate:()=>void;tick:()=>void;setScope:(scope:'stone'|'journey')=>void;setEvent:(event:string)=>void;advance:()=>void};
export function context(s:Pick<State,'era'|'event'|'mode'|'cards'|'discovered'>):Context{return {era:s.era,event:s.event,known:s.mode==='challenge'?[...BASE.map(c=>c.id),...s.discovered]:s.cards.map(c=>c.id)};}
export function available(s:State){const ctx=context(s);return s.cards.filter(c=>eligible(c,ctx)&&(s.mode==='sandbox'||c.depth===0||s.discovered.includes(c.id)));}
export const credits=(s:Pick<State,'mode'|'roundCredits'|'researchCredits'>)=>s.mode==='challenge'?s.roundCredits:s.researchCredits;
function save(s:State){try{localStorage.setItem('paperbound-v2',JSON.stringify({version:2,cards:s.cards,journal:s.journal,scope:s.scope,era:s.era,event:s.event,researchCredits:s.researchCredits,researchProgress:s.researchProgress,helperId:s.helperId,favorites:s.favorites,milestones:s.milestones}));}catch{useGame.setState({message:'เบราว์เซอร์บันทึกไม่ได้ ยังเล่นได้แต่ความคืบหน้าอาจไม่ถูกเก็บ'});}}
export const useGame=create<State>((set,get)=>({feedback:null,researchCredits:3,roundCredits:2,researchProgress:0,researchGoal:'any',researchResult:null,helperId:null,helperEnabled:false,helperNextAt:0,favorites:[],milestones:[],lastMilestone:null,cards:BASE,journal:[],slots:[null,null],last:null,message:'เริ่มด้วย หิน + หิน แล้วลองต่อยอดกัน',mode:'sandbox',scope:'stone',era:'stone',event:'clear',deadline:0,round:1,score:0,roundIds:[],discovered:[],done:false,hydrated:false,
 hydrate:()=>{try{const d=JSON.parse(localStorage.getItem('paperbound-v2')??'null');if(d?.version===2&&Array.isArray(d.cards)){const restored=d.cards.slice(0,50000).map(restoreCard).filter(Boolean) as Card[];const cards=[...new Map([...BASE,...restored].map(c=>[c.id,c])).values()];const journal=Array.isArray(d.journal)?d.journal.filter((e:Entry)=>typeof e.a==='string'&&typeof e.b==='string'&&e.result&&restoreCard(e.result.card)).slice(0,10000):[];const scope=d.scope==='journey'?'journey':'stone';set({cards,journal,scope,researchCredits:Number.isInteger(d.researchCredits)?Math.max(0,Math.min(5,d.researchCredits)):3,researchProgress:Number.isInteger(d.researchProgress)?Math.max(0,d.researchProgress)%5:0,helperId:HELPERS.some(h=>h.id===d.helperId)?d.helperId:null,favorites:Array.isArray(d.favorites)?d.favorites.filter((id:unknown)=>typeof id==='string').slice(0,5000):[],milestones:Array.isArray(d.milestones)?d.milestones.filter((id:unknown)=>MILESTONES.some(m=>m.id===id)):[],era:scope==='journey'&&d.era==='bronze'?'bronze':'stone',event:['clear','cold','rain'].includes(d.event)?d.event:'clear'});}}catch{}set({hydrated:true});},
 add:(card,index)=>set(s=>{if(s.mode==='challenge'&&(s.done||Date.now()>=s.deadline))return {};const c=available(s).find(c=>c.id===card.id);if(!c)return {message:'ค้นพบวัสดุนี้ในยุคปัจจุบันก่อน'};const slots=[...s.slots];slots[index??(slots[0]?1:0)]=c;return {slots,message:'พร้อมแล้ว! กดทดลองผสมได้เลย'};}),
 clear:()=>set({slots:[null,null],message:'โต๊ะว่างแล้ว ลองคู่ใหม่กัน'}),
 craft:()=>{const s=get();if(s.mode==='challenge'&&(s.done||Date.now()>=s.deadline)){set({done:true});return;}const [a,b]=s.slots;if(!a||!b)return;const owned=new Set(available(s).map(c=>c.id));if(!owned.has(a.id)||!owned.has(b.id)){set({slots:[null,null],message:'ยังไม่มีวัสดุนี้ในการสำรวจรอบนี้'});return;}const {result,reason}=reaction(a,b,context(s));if(!result){set({last:null,message:reason,feedback:{id:(s.feedback?.id??0)+1,kind:"fail",points:0}});return;}const isNew=!s.cards.some(c=>c.id===result.card.id);const cards=isNew?[...s.cards,result.card]:s.cards;const journal=s.journal.some(e=>[e.aId,e.bId].sort().join('|')===[a.id,b.id].sort().join('|'))?s.journal:[{a:a.name,b:b.name,aId:a.id,bId:b.id,result,time:Date.now()},...s.journal];const sessionNew=!s.discovered.includes(result.card.id);const earn=s.mode==='sandbox'?isNew:sessionNew;const milestone=earn?MILESTONES.find(m=>m.card===result.card.id&&!s.milestones.includes(m.id)):null;const progress=s.researchProgress+(isNew?1:0);set({feedback:{id:(s.feedback?.id??0)+1,kind:"success",points:(earn?points(result,s.event):0)+(milestone?.bonus??0)},researchProgress:progress%5,researchCredits:Math.min(5,s.researchCredits+(progress>=5?1:0)),milestones:milestone?[...s.milestones,milestone.id]:s.milestones,lastMilestone:milestone?`${milestone.name} · +${milestone.bonus} VP`:null,researchResult:s.researchResult?.result.card.id===result.card.id?null:s.researchResult,cards,journal,last:result,message:earn?`Discovery! +${points(result,s.event)} points. Try using it in your next experiment.`:'Already discovered. Try a different property to find something new.',slots:[null,null],score:s.score+(earn?points(result,s.event):0)+(milestone?.bonus??0),roundIds:sessionNew?[...s.roundIds,result.card.id]:s.roundIds,discovered:sessionNew?[...s.discovered,result.card.id]:s.discovered});save(get());},
 start:mode=>{set({roundCredits:2,researchResult:null,helperEnabled:false,helperNextAt:0,lastMilestone:null,mode,era:'stone',deadline:mode==='challenge'?Date.now()+45000:0,round:1,score:0,roundIds:[],discovered:[],done:false,slots:[null,null],last:null,message:mode==='challenge'?'มีเวลา 45 วินาที ค้นพบไฟและต่อยอดความรู้กัน':'ทดลองได้อิสระ วัสดุใช้ซ้ำได้'});save(get());},
 next:()=>set(s=>s.round<3&&s.done?{roundCredits:2,researchResult:null,round:s.round+1,deadline:Date.now()+45000,done:false,roundIds:[],slots:[null,null]}:{}),
 tick:()=>{const s=get();if(s.mode==='challenge'&&!s.done&&Date.now()>=s.deadline)set({done:true,slots:[null,null]});},
 setScope:scope=>{set({researchResult:null,helperEnabled:false,helperNextAt:0,scope,era:'stone',mode:'sandbox',done:false,slots:[null,null],last:null,message:scope==='stone'?'โหมดยุคหิน ใช้ความรู้เฉพาะยุคนี้':'โหมดเดินทาง ทำเป้าหมายให้ครบเพื่อเปิดยุคสำริด'});save(get());},
 setEvent:event=>{if(!['clear','cold','rain'].includes(event)||get().mode==='challenge')return;set({event,researchResult:null,slots:[null,null],message:'สภาพแวดล้อมเปลี่ยนแล้ว ดูกติกาก่อนทดลอง'});save(get());},
 advance:()=>{const s=get();if(s.scope!=='journey'||s.era!=='stone'||s.mode==='challenge'&&(s.done||Date.now()>=s.deadline)||!advanceRequirements(context(s).known).every(r=>r.met))return;const raw=[CARDS.get('copper_ore')!,CARDS.get('tin_ore')!];set({researchResult:null,era:'bronze',cards:[...new Map([...s.cards,...raw].map(c=>[c.id,c])).values()],slots:[null,null],message:'เปิดยุคสำริดแล้ว! มีสินแร่ให้ใช้ สร้างเตาหลอมกัน'});save(get());}
 ,setResearchGoal:goal=>{if(goal!=='any'&&!['firecraft','toolmaking','pottery','cultivation','metallurgy'].includes(goal))return;set({researchGoal:goal,researchResult:null});},
 study:()=>{const s=get();if(s.mode==='challenge'&&(s.done||Date.now()>=s.deadline))return;
 if(s.researchResult&&!available(s).some(c=>c.id===s.researchResult!.result.card.id)){set({message:'มีสูตรวิจัยรออยู่ เลือกวัสดุไปทดลองก่อน'});return;}
 if(credits(s)<1){set({message:'โควตาหมดแล้ว ค้นพบใหม่ 5 ชิ้นเพื่อรับเพิ่ม หรือรอรอบถัดไป'});return;}
 const plan=researchPlan(available(s),context(s),s.researchGoal);if(!plan){set({message:'ยังไม่มีสูตรที่วิจัยได้ในยุคนี้ ไม่เสียโควตา'});return;}
 set({...s.mode==='challenge'?{roundCredits:s.roundCredits-1}:{researchCredits:s.researchCredits-1},researchResult:plan,message:'วิจัยสำเร็จ! มีสูตรใหม่ให้ลอง'});save(get());},
 loadPair:ids=>{const s=get();if(s.mode==='challenge'&&(s.done||Date.now()>=s.deadline))return;const owned=new Map(available(s).map(c=>[c.id,c]));const a=owned.get(ids[0]),b=owned.get(ids[1]);if(!a||!b){set({message:'ค้นพบวัสดุทั้งสองในการสำรวจนี้ก่อน'});return;}set({slots:[a,b],message:'เลือกวัสดุแล้ว พร้อมเมื่อไรกดทดลองเลย'});},
 hireHelper:()=>{const s=get();if(s.mode!=='sandbox'){set({message:'ผู้ช่วยใช้ได้ในโหมดอิสระ'});return;}if(s.helperId){set({message:'มีผู้ช่วยแล้ว'});return;}const helper=HELPERS[0];if(!helper.requires.every(id=>knowledge(context(s).known).has(id))){set({message:'ค้นพบไฟและเครื่องมือเพื่อเปิดรับผู้ช่วย'});return;}if(s.researchCredits<1){set({message:'รับผู้ช่วยต้องใช้โควตาวิจัย 1 หน่วย'});return;}set({helperId:helper.id,researchCredits:s.researchCredits-1,helperEnabled:false,message:'รับนักทดลองประจำค่ายแล้ว กดเปิดเมื่ออยากให้ช่วย'});save(get());},
 toggleHelper:()=>{const s=get();if(s.mode!=='sandbox'||!s.helperId)return;set({helperEnabled:!s.helperEnabled,helperNextAt:Date.now()+12000,message:s.helperEnabled?'พักผู้ช่วยแล้ว':'ผู้ช่วยเริ่มทำงาน ใช้โควตาวิจัย 1 หน่วยต่อการทดลอง'});},
 helperTick:(now=Date.now())=>{const s=get();if(s.mode!=='sandbox'||!s.helperId||!s.helperEnabled||s.researchCredits<1||now<s.helperNextAt||s.slots.some(Boolean))return;
 if(!HELPERS[0].requires.every(id=>knowledge(context(s).known).has(id)))return;
 const owned=available(s);const plan=researchPlan(owned,context(s),s.researchGoal);if(!plan){set({helperEnabled:false,message:'ผู้ช่วยพัก เพราะยังไม่มีสูตรใหม่ที่ทดลองได้'});return;}
 const a=owned.find(c=>c.id===plan.ingredients[0]),b=owned.find(c=>c.id===plan.ingredients[1]);if(!a||!b)return;
 set({slots:[a,b],researchCredits:s.researchCredits-1,helperNextAt:now+12000});get().craft();set({message:'ผู้ช่วยทดลองสำเร็จ ใช้โควตาวิจัย 1 หน่วย'});save(get());},
 toggleFavorite:id=>{const s=get();if(!s.cards.some(c=>c.id===id))return;set({favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]});save(get());}
}));
