import {create} from 'zustand';
import {BASE,CARDS,type Card,type Context,type Era,type Result,advanceRequirements,eligible,points,reaction,restoreCard} from './engine.ts';
export type Entry={a:string;b:string;aId:string;bId:string;result:Result;time:number};
type State={cards:Card[];journal:Entry[];slots:(Card|null)[];last:Result|null;message:string;mode:'sandbox'|'challenge';scope:'stone'|'journey';era:Era;event:string;deadline:number;round:number;score:number;roundIds:string[];discovered:string[];done:boolean;hydrated:boolean;add:(c:Card,index?:number)=>void;clear:()=>void;craft:()=>void;start:(mode:'sandbox'|'challenge')=>void;next:()=>void;hydrate:()=>void;tick:()=>void;setScope:(scope:'stone'|'journey')=>void;setEvent:(event:string)=>void;advance:()=>void};
export function context(s:Pick<State,'era'|'event'|'mode'|'cards'|'discovered'>):Context{return {era:s.era,event:s.event,known:s.mode==='challenge'?[...BASE.map(c=>c.id),...s.discovered]:s.cards.map(c=>c.id)};}
export function available(s:State){const ctx=context(s);return s.cards.filter(c=>eligible(c,ctx)&&(s.mode==='sandbox'||c.depth===0||s.discovered.includes(c.id)));}
function save(s:State){try{localStorage.setItem('paperbound-v2',JSON.stringify({version:2,cards:s.cards,journal:s.journal,scope:s.scope,era:s.era,event:s.event}));}catch{useGame.setState({message:'Browser storage is unavailable. This session still works, but progress may not be saved.'});}}
export const useGame=create<State>((set,get)=>({cards:BASE,journal:[],slots:[null,null],last:null,message:'Start with stone + stone. What can a sharper edge unlock?',mode:'sandbox',scope:'stone',era:'stone',event:'clear',deadline:0,round:1,score:0,roundIds:[],discovered:[],done:false,hydrated:false,
 hydrate:()=>{try{const d=JSON.parse(localStorage.getItem('paperbound-v2')??'null');if(d?.version===2&&Array.isArray(d.cards)){const restored=d.cards.slice(0,50000).map(restoreCard).filter(Boolean) as Card[];const cards=[...new Map([...BASE,...restored].map(c=>[c.id,c])).values()];const journal=Array.isArray(d.journal)?d.journal.filter((e:Entry)=>typeof e.a==='string'&&typeof e.b==='string'&&e.result&&restoreCard(e.result.card)).slice(0,10000):[];const scope=d.scope==='journey'?'journey':'stone';set({cards,journal,scope,era:scope==='journey'&&d.era==='bronze'?'bronze':'stone',event:['clear','cold','rain'].includes(d.event)?d.event:'clear'});}}catch{}set({hydrated:true});},
 add:(card,index)=>set(s=>{if(s.mode==='challenge'&&(s.done||Date.now()>=s.deadline))return {};const c=available(s).find(c=>c.id===card.id);if(!c)return {message:'Discover this ingredient in your current era first.'};const slots=[...s.slots];slots[index??(slots[0]?1:0)]=c;return {slots,message:'Ready to explore? Combine your ingredients.'};}),
 clear:()=>set({slots:[null,null],message:'A fresh start. Try another combination.'}),
 craft:()=>{const s=get();if(s.mode==='challenge'&&(s.done||Date.now()>=s.deadline)){set({done:true});return;}const [a,b]=s.slots;if(!a||!b)return;const owned=new Set(available(s).map(c=>c.id));if(!owned.has(a.id)||!owned.has(b.id)){set({slots:[null,null],message:'These ingredients are not available in this expedition.'});return;}const {result,reason}=reaction(a,b,context(s));if(!result){set({last:null,message:reason});return;}const isNew=!s.cards.some(c=>c.id===result.card.id);const cards=isNew?[...s.cards,result.card]:s.cards;const journal=s.journal.some(e=>[e.aId,e.bId].sort().join('|')===[a.id,b.id].sort().join('|'))?s.journal:[{a:a.name,b:b.name,aId:a.id,bId:b.id,result,time:Date.now()},...s.journal];const sessionNew=!s.discovered.includes(result.card.id);const earn=s.mode==='sandbox'?isNew:sessionNew;set({cards,journal,last:result,message:earn?`Discovery! +${points(result,s.event)} points. Try using it in your next experiment.`:'Already discovered. Try a different property to find something new.',slots:[null,null],score:s.score+(earn?points(result,s.event):0),roundIds:sessionNew?[...s.roundIds,result.card.id]:s.roundIds,discovered:sessionNew?[...s.discovered,result.card.id]:s.discovered});save(get());},
 start:mode=>{set({mode,era:'stone',deadline:mode==='challenge'?Date.now()+45000:0,round:1,score:0,roundIds:[],discovered:[],done:false,slots:[null,null],last:null,message:mode==='challenge'?'45 seconds. Rediscover fire and build your knowledge.':'Experiment freely. Ingredients can be reused.'});save(get());},
 next:()=>set(s=>s.round<3?{round:s.round+1,deadline:Date.now()+45000,done:false,roundIds:[],slots:[null,null]}:{}),
 tick:()=>{const s=get();if(s.mode==='challenge'&&!s.done&&Date.now()>=s.deadline)set({done:true,slots:[null,null]});},
 setScope:scope=>{set({scope,era:'stone',mode:'sandbox',done:false,slots:[null,null],last:null,message:scope==='stone'?'Stone Age only: innovation stays within this era.':'Journey mode: meet all milestones to open the Bronze Age.'});save(get());},
 setEvent:event=>{if(!['clear','cold','rain'].includes(event)||get().mode==='challenge')return;set({event,slots:[null,null],message:'Conditions changed. Check the event rule before experimenting.'});save(get());},
 advance:()=>{const s=get();if(s.scope!=='journey'||s.era!=='stone'||s.mode==='challenge'&&(s.done||Date.now()>=s.deadline)||!advanceRequirements(context(s).known).every(r=>r.met))return;const raw=[CARDS.get('copper_ore')!,CARDS.get('tin_ore')!];set({era:'bronze',cards:[...new Map([...s.cards,...raw].map(c=>[c.id,c])).values()],slots:[null,null],message:'Bronze Age unlocked! Ore is available. Build a furnace to refine it.'});save(get());}
}));
