import {Component,useEffect,useRef,useState,type ReactNode,type RefObject} from 'react';
import {Canvas,useFrame,useThree,type ThreeEvent} from '@react-three/fiber';
import {MOUSE,TOUCH,Group,OrthographicCamera,Plane,Raycaster,Vector2,Vector3} from 'three';
import {Hand,Pause,Play,MapPin,Users,Droplets,FlaskConical,UserPlus,Package,Plus,Minus} from 'lucide-react';
import {BUILD,TILES,assigned,buildingStatus,type Village,type Building,type Decoration} from '../model';
import {BuildingModel,DecorationModel,Tree,Villager} from './Models';
import {tilePosition,groundTile,type SceneHandle} from './layout';
import {worldHints,type WorldHint} from '../guidance';
import {landOffset,LAND_NAMES,NODE_NAMES} from '../land';
import {ResourceNodes} from './ResourceNodes';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const ground=new Plane(new Vector3(0,1,0),0);
type Props={now:number;onResearch:()=>void;onNode:(id:string)=>void;v:Village;selected:number|null;placing:Building|null;decorating:Decoration|null;moving:number|null;onChoose:(tile:number)=>void;onPeople:()=>void;onMove:(from:number,to:number)=>void;handle:RefObject<SceneHandle|null>};
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function CameraAndClock({handle,animate,tiles,view,navigate}:{navigate:boolean;handle:Props['handle'];animate:boolean;tiles:number;view:{x:number;zoom:number;revision:number}}){
 const controls=useRef<OrbitControls|null>(null);const {camera,size,gl,invalidate}=useThree();useEffect(()=>{const c=camera as OrthographicCamera;c.position.set(9+view.x,11,12);c.lookAt(view.x,.2,-.8);c.zoom=Math.min(size.width/14,size.height/11)*view.zoom;c.updateProjectionMatrix();invalidate();},[camera,size.width,size.height,invalidate,view.x,view.zoom,view.revision]);
 useEffect(()=>{const c=new OrbitControls(camera,gl.domElement);controls.current=c;c.enableRotate=false;c.enableDamping=false;c.screenSpacePanning=false;c.mouseButtons.LEFT=MOUSE.PAN;c.touches.ONE=TOUCH.PAN;c.touches.TWO=TOUCH.DOLLY_PAN;c.target.set(view.x,.2,-.8);c.minZoom=Math.min(size.width/14,size.height/11)*.55;c.maxZoom=c.minZoom/.55*1.8;c.enabled=navigate;c.addEventListener('change',()=>invalidate());return()=>{c.dispose();controls.current=null;};},[camera,gl,invalidate,view.x,view.zoom,view.revision,size.width,size.height]);
 useEffect(()=>{if(controls.current)controls.current.enabled=navigate;},[navigate]);
 useEffect(()=>{const caster=new Raycaster(),xy=new Vector2(),point=new Vector3();handle.current={tileAt:p=>{const rect=gl.domElement.getBoundingClientRect();if(p.x<rect.left||p.x>rect.right||p.y<rect.top||p.y>rect.bottom)return null;xy.set((p.x-rect.left)/rect.width*2-1,-(p.y-rect.top)/rect.height*2+1);caster.setFromCamera(xy,camera);return caster.ray.intersectPlane(ground,point)?groundTile(point.x,point.z,tiles):null;}};return()=>{handle.current=null;};},[camera,gl,handle,tiles]);
 useEffect(()=>{if(!animate){invalidate();return;}const interval=setInterval(()=>{if(!document.hidden)invalidate();},1000/30);return()=>clearInterval(interval);},[animate,invalidate]);return null;
}
// DOM buttons stay accessible while their anchors follow the orthographic camera.
function HintAnchors({hints,elements}:{hints:WorldHint[];elements:RefObject<Map<number,HTMLButtonElement>>}){
 const {camera,size}=useThree();
 useFrame(()=>{const occupied:{x:number;y:number}[]=[];for(const hint of hints){const element=elements.current.get(hint.tile);if(!element)continue;const [x,,z]=tilePosition(hint.tile),p=new Vector3(x,1.65,z).project(camera);const left=(p.x+1)*size.width/2,top=(1-p.y)*size.height/2;const visible=left>=24&&left<=size.width-24&&top>=24&&top<=size.height-24&&!occupied.some(a=>Math.hypot(a.x-left,a.y-top)<50);element.style.visibility=visible?'visible':'hidden';element.style.transform=`translate(${left-22}px,${top-22}px)`;if(visible)occupied.push({x:left,y:top});}});
 return null;
}
function ResearchStation({motion,onChoose,element}:{motion:boolean;onChoose:()=>void;element:RefObject<HTMLButtonElement|null>}){
 const group=useRef<Group>(null),{camera,size}=useThree();useFrame(({clock})=>{if(group.current)group.current.rotation.y=motion?Math.sin(clock.elapsedTime*.8)*.025:0;const p=new Vector3(-.5,1.45,3.15).project(camera),left=(p.x+1)*size.width/2,top=(1-p.y)*size.height/2,button=element.current;if(button){const visible=left>=24&&left<=size.width-24&&top>=24&&top<=size.height-24;button.style.visibility=visible?'visible':'hidden';button.style.transform=`translate(${left-22}px,${top-22}px)`;}});
 return <group ref={group} position={[-.5,0,3.15]} onClick={e=>{e.stopPropagation();if(e.delta<7)onChoose();}}><mesh position={[0,.55,0]} castShadow><boxGeometry args={[1.25,.12,.75]}/><meshStandardMaterial color="#b28c68" roughness={1}/></mesh>{[-.48,.48].flatMap(x=>[-.25,.25].map(z=><mesh key={x+'-'+z} position={[x,.27,z]} castShadow><boxGeometry args={[.1,.55,.1]}/><meshStandardMaterial color="#8d7058"/></mesh>))}<mesh position={[-.27,.72,0]} rotation={[0,.2,0]} castShadow><boxGeometry args={[.38,.08,.5]}/><meshStandardMaterial color="#f1dfb8"/></mesh><mesh position={[.27,.73,0]} rotation={[0,-.2,0]} castShadow><boxGeometry args={[.38,.08,.5]}/><meshStandardMaterial color="#ead5a9"/></mesh><mesh position={[.4,1.02,.12]} castShadow><coneGeometry args={[.17,.4,8]}/><meshStandardMaterial color="#9fc7ba" transparent opacity={.9}/></mesh><mesh position={[.4,.82,.12]} castShadow><cylinderGeometry args={[.1,.14,.22,8]}/><meshStandardMaterial color="#d7af79"/></mesh></group>;
}
function ObjectAt({tile,kind,motion,onChoose,onMove,selected,rotation,tiles,navigate}:{navigate:boolean;rotation:number;tiles:number;tile:number;kind:Building;motion:boolean;onChoose:Props['onChoose'];onMove:Props['onMove'];selected:boolean}){
 const model=useRef<Group>(null),start=useRef<{x:number;y:number;drag:boolean;pointer:number;ox:number;oz:number}|null>(null);const position=tilePosition(tile);
 function reset(){if(model.current)model.current.position.set(...position);start.current=null;}
 useEffect(()=>reset(),[tile,kind]);
 function down(e:ThreeEvent<PointerEvent>){if(navigate||e.button!==0)return;e.stopPropagation();const p=e.ray.intersectPlane(ground,new Vector3());start.current={x:e.clientX,y:e.clientY,drag:false,pointer:e.pointerId,ox:(p?.x??position[0])-position[0],oz:(p?.z??position[2])-position[2]};(e.target as Element).setPointerCapture(e.pointerId);}
 function move(e:ThreeEvent<PointerEvent>){const s=start.current;if(!s)return;e.stopPropagation();if(Math.hypot(e.clientX-s.x,e.clientY-s.y)<7&&!s.drag)return;s.drag=true;const p=new Vector3();if(e.ray.intersectPlane(ground,p)&&model.current)model.current.position.set(Math.max(tiles>=24?-12:-4,Math.min(tiles>=36?12:4,p.x-s.ox)),.25,Math.max(-3,Math.min(3,p.z-s.oz)));}
 function up(e:ThreeEvent<PointerEvent>){const s=start.current;if(!s)return;e.stopPropagation();const p=new Vector3(),destination=e.ray.intersectPlane(ground,p)?groundTile(p.x-s.ox,p.z-s.oz,tiles):null;if((e.target as Element).hasPointerCapture(e.pointerId))(e.target as Element).releasePointerCapture(e.pointerId);reset();if(s.drag){if(destination!==null)onMove(tile,destination);}else onChoose(tile);}
 return <group><group ref={model} position={position} onClick={e=>e.stopPropagation()} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={reset}><group rotation={[0,rotation*Math.PI/180,0]}><BuildingModel kind={kind} motion={motion}/></group></group>{selected&&<mesh position={[position[0],.025,position[2]]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.85,.93,48]}/><meshBasicMaterial color="#e7ad65"/></mesh>}</group>;
}
function World(props:Props&{navigate:boolean;view:{x:number;zoom:number;revision:number};nodeElements:RefObject<Map<string,HTMLButtonElement>>;researchElement:RefObject<HTMLButtonElement|null>;motion:boolean;hints:WorldHint[];elements:RefObject<Map<number,HTMLButtonElement>>}){
 const {v,placing,decorating,moving,onChoose,onMove,selected,motion}=props;const intended=placing??(moving!==null?v.plots[moving]:null);
 return <><HintAnchors hints={props.hints} elements={props.elements}/><CameraAndClock handle={props.handle} animate={motion} tiles={v.plots.length} view={props.view} navigate={props.navigate}/><ambientLight intensity={1.6}/><hemisphereLight args={['#fff4da','#a9b68c',1.5]}/><directionalLight position={[-5,10,5]} intensity={2.3} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-9} shadow-camera-right={9} shadow-camera-top={9} shadow-camera-bottom={-9} shadow-normalBias={.04}/>
 <ResourceNodes nodes={v.nodes} motion={motion} onChoose={props.onNode} elements={props.nodeElements}/><ResearchStation motion={motion} onChoose={props.onResearch} element={props.researchElement}/>{Array.from({length:v.plots.length/12},(_,i)=><group key={i} position={[landOffset(i),0,0]}><mesh position={[0,-.34,-.5]} receiveShadow><boxGeometry args={[8,.65,9]}/><meshStandardMaterial color="#c9c3a0"/></mesh><mesh position={[0,-.035,-.5]} receiveShadow><boxGeometry args={[8,.07,9]}/><meshStandardMaterial color={i===1?"#bdd2aa":i===2?"#d8d0b4":"#c9d7b3"}/></mesh></group>)}
 <mesh position={[4.1,.008,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[1.2,7.2]}/><meshStandardMaterial color="#a6ccc6" roughness={.6}/></mesh>
 {[-2.7,-1.5,0,1.6,2.7].map((z,i)=><mesh key={z} position={[4.12,.02,z]} rotation={[-Math.PI/2,0,.2]}><planeGeometry args={[.6,.03]}/><meshBasicMaterial color="#d6e9df"/></mesh>)}
 <mesh position={[0,.008,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[7.8,.25]}/><meshStandardMaterial color="#ddd1b1"/></mesh>

 {TILES.slice(0,v.plots.length).map((terrain,i)=>{const [x,,z]=tilePosition(i);const show=decorating?!v.decorations[i]:intended&&!v.plots[i]&&(!BUILD[intended].terrain||BUILD[intended].terrain===terrain);return <group key={i}><mesh position={[x,.015,z]} rotation={[-Math.PI/2,0,0]} onClick={e=>{e.stopPropagation();if(e.delta<7)onChoose(i);}}><planeGeometry args={[1.85,1.85]}/><meshBasicMaterial color={show?'#f4e5b4':'#ffffff'} transparent opacity={show ? .45 : 0} depthWrite={false}/></mesh>{show&&<mesh position={[x,.022,z]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.69,.72,40]}/><meshBasicMaterial color="#809e6c"/></mesh>}</group>;})}
 {v.plots.map((b,i)=>b&&<ObjectAt key={i+'-'+b} kind={b} tile={i} rotation={v.rotations[i]} tiles={v.plots.length} navigate={props.navigate} motion={motion} onChoose={onChoose} onMove={onMove} selected={selected===i}/>)}
 {v.decorations.map((d,i)=>d&&<group key={i} position={[tilePosition(i)[0]-.48,.04,tilePosition(i)[2]+.42]} scale={.8} onClick={e=>{e.stopPropagation();onChoose(i);}}><DecorationModel kind={d} motion={motion}/></group>)}
 {Array.from({length:v.people},(_,i)=><group key={i} onClick={e=>{e.stopPropagation();props.onPeople();}}><Villager index={i} motion={motion} working={i<assigned(v)}/></group>)}
 </>;
}
export default function WorldScene(props:Props){
 const [navigate,setNavigate]=useState(false);const [view,setView]=useState({x:0,zoom:1,revision:0});const nodeElements=useRef(new Map<string,HTMLButtonElement>()),researchElement=useRef<HTMLButtonElement|null>(null);
 const [motion,setMotion]=useState(true),[reduced,setReduced]=useState(false),[list,setList]=useState(false),[visible,setVisible]=useState(true),[lost,setLost]=useState(false);const host=useRef<HTMLDivElement>(null);const elements=useRef(new Map<number,HTMLButtonElement>());const hints=props.placing||props.decorating||props.moving!==null?[]:worldHints(props.v).filter(h=>h.tile!==props.selected);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)'),changed=()=>setReduced(q.matches);changed();q.addEventListener('change',changed);const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting));if(host.current)observer.observe(host.current);return()=>{q.removeEventListener('change',changed);observer.disconnect();};},[]);
 const fallback=<div className="world-fallback"><p>อุปกรณ์นี้เปิดฉาก 3D ไม่ได้ ใช้รายการวัตถุด้านล่างเพื่อเล่นต่อ</p><button onClick={()=>setList(true)}>เปิดรายการวัตถุ</button></div>;
 return <div ref={host} className="three-world" aria-label="หมู่บ้าน 2.5D แบบโต้ตอบ"><SceneBoundary fallback={fallback}>{lost?fallback:<Canvas orthographic frameloop="demand" dpr={[1,1.5]} shadows camera={{position:[9,11,12],near:.1,far:100,zoom:40}} gl={{antialias:true,alpha:true,powerPreference:'low-power'}} fallback={fallback} onCreated={({gl})=>{gl.domElement.setAttribute('aria-label','ฉากหมู่บ้าน: แตะอาคารเพื่อใช้งาน หรือลากเพื่อย้าย');gl.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();setLost(true);},{once:true});}}><World {...props} onChoose={navigate?()=>{}:props.onChoose} onNode={navigate?()=>{}:props.onNode} onPeople={navigate?()=>{}:props.onPeople} onResearch={navigate?()=>{}:props.onResearch} navigate={navigate} view={view} nodeElements={nodeElements} researchElement={researchElement} hints={hints} elements={elements} motion={motion&&!reduced&&visible}/></Canvas>}</SceneBoundary>
 <div className="land-navigation">{navigate&&<span className="pan-label">ลากเพื่อเลื่อน · บีบเพื่อซูม</span>}{LAND_NAMES.slice(0,props.v.plots.length/12).map((n,i)=><button key={n} aria-pressed={view.x===landOffset(i)} onClick={()=>setView({...view,x:landOffset(i),revision:view.revision+1})}>{n}</button>)}<button aria-label="ซูมออก" onClick={()=>setView({...view,zoom:Math.max(.55,view.zoom-.2)})}><Minus size={16}/></button><button aria-label="ซูมเข้า" onClick={()=>setView({...view,zoom:Math.min(1.8,view.zoom+.2)})}><Plus size={16}/></button></div>
 <div className="scene-tools"><button className="icon-button" aria-label={navigate?"กลับไปแตะวัตถุ":"เลื่อนฉาก: ลากหนึ่งนิ้ว บีบสองนิ้วซูม"} aria-pressed={navigate} onClick={()=>setNavigate(!navigate)}><Hand size={18}/></button><button className="icon-button" aria-label="รายการวัตถุและพื้นที่" aria-expanded={list} onClick={()=>setList(!list)}><MapPin size={18}/></button><button className="icon-button" disabled={reduced} aria-label={motion?'พักการเคลื่อนไหว':'เปิดการเคลื่อนไหว'} onClick={()=>setMotion(!motion)}>{motion&&!reduced?<Pause size={18}/>:<Play size={18}/>}</button></div>
 {!lost&&!list&&<div className="world-hints">{props.v.nodes.filter(n=>n.chunk===(view.x===-8?1:view.x===8?2:0)).map(n=><button key={n.id} className="world-hint node-hint" ref={el=>{if(el)nodeElements.current.set(n.id,el);else nodeElements.current.delete(n.id);}} style={{visibility:'hidden'}} aria-label={NODE_NAMES[n.resource]+(n.stored?' พร้อมเก็บ '+n.stored:' กำลังฟื้นตัว')} onClick={()=>props.onNode(n.id)}>{n.stored?<><Package size={16}/><small>{n.stored}</small></>:<small>{Math.max(0,Math.ceil((n.readyAt-props.v.lastActiveAt)/1000))}วิ</small>}</button>)}</div>}
 {!lost&&!list&&<div className="world-hints"><button ref={researchElement} className={'world-hint research-hint '+(props.v.research.length?'active':'')} style={{visibility:'hidden'}} aria-label={props.v.research.length?`โต๊ะวิจัย เหลือ ${Math.max(0,Math.ceil((props.v.research[0].finishAt-props.now)/1000))} วินาที`:'เปิดโต๊ะวิจัย'} onClick={props.onResearch}><FlaskConical size={18}/>{props.v.research.length>0&&<small>{Math.max(0,Math.ceil((props.v.research[0].finishAt-props.now)/1000))}</small>}</button></div>}
 {!lost&&!list&&<div className="world-hints" aria-label="สิ่งที่หมู่บ้านต้องการ">{hints.map(h=>{const Icon={people:Users,water:Droplets,craft:FlaskConical,welcome:UserPlus}[h.kind];return <button key={h.tile} ref={el=>{if(el)elements.current.set(h.tile,el);else elements.current.delete(h.tile);}} className={'world-hint '+h.kind} style={{visibility:'hidden'}} aria-label={h.label} title={h.label} onClick={()=>props.onChoose(h.tile)}><Icon size={21}/></button>;})}</div>}

 {list&&<div className="scene-object-list"><button onClick={()=>setList(false)}>ปิดรายการ</button><button onClick={()=>{props.onResearch();setList(false);}}>โต๊ะวิจัย · {props.v.research.length?'มี '+props.v.research.length+' งาน':'พร้อมทดลอง'}</button><button onClick={()=>{props.onPeople();setList(false);}}>เลือกชาวบ้านและจัดงาน</button>{props.v.nodes.map(n=><button key={n.id} onClick={()=>{props.onNode(n.id);setList(false);}}>{LAND_NAMES[n.chunk]} · {NODE_NAMES[n.resource]} · พร้อมเก็บ {n.stored}</button>)}{TILES.slice(0,props.v.plots.length).map((t,i)=><button key={i} onClick={()=>{props.onChoose(i);setList(false);}}>{i+1} · {props.v.plots[i]?BUILD[props.v.plots[i]!].name:t==='forest'?'พื้นที่ใกล้ป่า':t==='river'?'พื้นที่ริมน้ำ':'พื้นที่ว่าง'}</button>)}</div>}
 </div>;
}
