import test from 'node:test';
import assert from 'node:assert/strict';
import {BASE,CARDS,type Context} from '../src/game/engine.ts';
import {researchPlan,newPartners} from '../src/game/research.ts';
import {useGame,credits} from '../src/game/store.ts';
import {indexCards,filterCards} from '../src/game/collection.ts';
const card=(id:string)=>CARDS.get(id)!;
const ctx:Context={era:'stone',known:BASE.map(c=>c.id),event:'clear'};
const memory=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{setItem:(k:string,v:string)=>memory.set(k,v),getItem:(k:string)=>memory.get(k)??null}});
function reset(){useGame.setState({cards:[...BASE],journal:[],slots:[null,null],mode:'sandbox',scope:'stone',era:'stone',event:'clear',score:0,discovered:[],roundIds:[],done:false,round:1,deadline:0,researchCredits:3,roundCredits:2,researchProgress:0,researchGoal:'any',researchResult:null,helperId:null,helperEnabled:false,helperNextAt:0,milestones:[],favorites:[]});}
test('targeted fire research reveals flint first; learned and locked goals spend nothing',()=>{const p=researchPlan(BASE,ctx,'firecraft');assert.equal(p?.result.card.id,'flint');assert.deepEqual(p?.ingredients,['stone','stone']);assert.equal(researchPlan(BASE,ctx,'metallurgy'),null);reset();useGame.getState().setResearchGoal('metallurgy');useGame.getState().study();assert.equal(credits(useGame.getState()),3);});
test('research consumes exactly one credit, does not grant item or points, and duplicate reveal is free',()=>{reset();const g=()=>useGame.getState();g().setResearchGoal('firecraft');g().study();assert.equal(g().researchCredits,2);assert.equal(g().score,0);assert.equal(g().cards.length,BASE.length);g().study();assert.equal(g().researchCredits,2);g().loadPair(g().researchResult!.ingredients);assert.deepEqual(g().slots.map(c=>c?.id),['stone','stone']);g().craft();assert.equal(g().researchResult,null);});
test('rich highlights contain only feasible undiscovered results, including duplicate ingredients',()=>{const partners=newPartners(card('stone'),BASE,ctx);assert.ok(partners.has('stone'));assert.ok(!partners.has('metal'));const known=[...BASE,card('flint')];assert.ok(!newPartners(card('stone'),known,{...ctx,known:known.map(c=>c.id)}).has('stone'));});
test('combined collection filters preserve favorites, properties, tiers and sorting',()=>{const cards=[...BASE,card('pottery'),card('flint')],index=indexCards(cards);assert.deepEqual(filterCards(index,'','favorites',{favorites:['flint'],tag:'mineral',tier:'1'}).map(c=>c.id),['flint']);assert.deepEqual(filterCards(index,'','partners',{partners:new Set(['stone'])}).map(c=>c.id),['stone']);assert.equal(filterCards(index,'','all',{era:'bronze'}).length,0);assert.equal(filterCards(index,'','all',{sort:'points'})[0].id,'pottery');});
test('assistant requires knowledge, honors quota and never overwrites a busy bench',()=>{reset();const g=()=>useGame.getState();g().hireHelper();assert.equal(g().helperId,null);useGame.setState({cards:[...BASE,card('fire'),card('tool')],researchGoal:'pottery'});g().hireHelper();assert.equal(g().researchCredits,2);g().toggleHelper();g().add(card('wood'));g().helperTick(Date.now()+20000);assert.equal(g().slots[0]?.id,'wood');assert.equal(g().researchCredits,2);g().clear();g().helperTick(Date.now()+20000);assert.equal(g().researchCredits,1);assert.ok(g().cards.some(c=>c.id==='clay'));assert.deepEqual(g().slots,[null,null]);useGame.setState({researchCredits:0});const length=g().cards.length;g().helperTick(Date.now()+60000);assert.equal(g().cards.length,length);});
test('assistant is paused in sprint, expired research spends nothing, round quota renews once',()=>{reset();const g=()=>useGame.getState();useGame.setState({helperId:'camp_tinkerer',helperEnabled:true});g().start('challenge');assert.equal(g().helperEnabled,false);assert.equal(credits(g()),2);useGame.setState({deadline:Date.now()-1});g().study();assert.equal(credits(g()),2);g().tick();g().next();assert.equal(credits(g()),2);assert.equal(g().round,2);});
test('milestone bonus is awarded once and repeated discoveries do not refill research',()=>{reset();const g=()=>useGame.getState();useGame.setState({cards:[...BASE,card('flint')]});g().loadPair(['flint','wood']);g().craft();const score=g().score,progress=g().researchProgress;assert.ok(g().milestones.includes('first_flame'));g().loadPair(['flint','wood']);g().craft();assert.equal(g().score,score);assert.equal(g().researchProgress,progress);});
