import {useState} from 'react';
import {BUILD,BUILDINGS,LABEL,RESOURCES,canPay,type Village,type Building,type Action} from './model';
import {buildReason} from './guidance';
import {ItemArt} from './scene/ItemArt';
export function BuildCatalog({v,dispatch,onPlace,onResearch}:{v:Village;dispatch:(a:Action)=>void;onPlace:(b:Building)=>void;onResearch:(b:Building)=>void}){
 const [query,setQuery]=useState(''),[readyOnly,setReadyOnly]=useState(false);
 const target=v.autoBuild,reason=target?buildReason(v,target):null;
 return <section className="build-catalog"><header><small>สมุดของผู้สร้าง</small><h2>ค่อย ๆ สร้างบ้านของเรา</h2><p>10 แบบก่อสร้าง · เลือกสูตร จัดหาวัสดุ แล้วเลือกที่วาง</p></header>
 {target&&<div className="auto-build-status" role="status"><ItemArt kind={target}/><div><strong>{!reason?'พร้อมวางแล้ว!':canPay(v,BUILD[target].cost)?'วัสดุครบ · ยังมีเงื่อนไข':'กำลังเตรียม '+BUILD[target].name}</strong><small>{reason??BUILD[target].name}</small><button disabled={!!reason} onClick={()=>onPlace(target)}>เลือกที่วาง</button><button onClick={()=>dispatch({type:'auto-build',building:null})}>หยุดช่วย</button></div></div>}
 <label className="catalog-search">ค้นหาแบบก่อสร้าง<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="บ้าน สวน เหมือง…"/></label><button className="catalog-filter" aria-pressed={readyOnly} onClick={()=>setReadyOnly(!readyOnly)}>{readyOnly?'✓ พร้อมวาง':'ดูเฉพาะพร้อมวาง'}</button>
 <div className="recipe-catalog-grid">{BUILDINGS.filter(b=>BUILD[b].name.includes(query)&&(!readyOnly||!buildReason(v,b))).map(b=>{const d=BUILD[b],locked=!!d.recipe&&!v.known.includes(d.recipe),blocked=buildReason(v,b);return <article className="construction-recipe" key={b}><div className="recipe-illustration"><ItemArt kind={b}/><span>{locked?'ต้องวิจัย':blocked?'เตรียมวัสดุ':'พร้อมวาง'}</span></div><h3>{d.name}</h3><p>{d.effect}</p><div className="recipe-costs">{RESOURCES.filter(r=>d.cost[r]).map(r=><span key={r} className={v.stock[r]>=(d.cost[r]??0)?'enough':'short'}><ItemArt kind={r}/><span>{LABEL[r]}<b>{v.stock[r]}/{d.cost[r]}</b></span></span>)}</div><small>{blocked??'เลือกตำแหน่งในหมู่บ้านได้เลย'}</small><button className="catalog-primary" onClick={()=>locked?onResearch(b):onPlace(b)} disabled={!locked&&!!blocked}>{locked?'เปิดสูตรวิจัย':'เลือกที่วาง'}</button><button className="catalog-auto" disabled={v.autoBuild===b} onClick={()=>dispatch({type:'auto-build',building:b})}>{v.autoBuild===b?'กำลังติดตามสูตรนี้':'ช่วยหาวัสดุอัตโนมัติ'}</button></article>;})}</div><p>ผู้ช่วยจัดงานคนแรกตามวัสดุที่ขาด รอบละ 30 วินาที ไม่เสกทรัพยากร ไม่วิจัยหรือสร้างแทนคุณ · พักได้สูงสุด 4 ชั่วโมง · วัสดุยังใช้ร่วมกับงานอื่น</p></section>;
}
