import {Flame,BrickWall,Check,Lock} from 'lucide-react';
import {has,canPay,type Village,type Action} from './model';
import {emptyIndustry} from './industry';
export function IndustryPanel({v,now,dispatch}:{v:Village;now:number;dispatch:(a:Action)=>void}){
 const p=v.industry??emptyIndustry(),titles=['ควบคุมความร้อน','เชื้อเพลิงชนิดใหม่','เริ่มงานก่ออิฐ'],goals=['สร้างเตาเผา 1 แห่ง','ผลิตถ่านไม้ 2 ชิ้น','ผลิตอิฐ 2 ก้อน'],rewards=['เปิดสูตรถ่าน + ไม้ 4','เปิดสูตรอิฐ + ดิน 4','โคมไฟตกแต่งฟรี 1 ชิ้น'],ready=p.claimed===0?has(v,'kiln'):p.claimed===1?p.charcoal>=2:p.brick>=2;
 return <section className="industry-panel"><header><small>เส้นทางอารยธรรม · บทงานช่าง</small><h2>จากกองไฟ สู่งานก่ออิฐ</h2></header><div className="industry-stock"><span><Flame/> ถ่านไม้ {p.charcoal}/40</span><span><BrickWall/> อิฐ {p.brick}/40</span></div>{titles.map((title,i)=><article className={'industry-quest '+(p.claimed===i?'current':'')} key={title}><span>{p.claimed>i?<Check/>:p.claimed<i?<Lock/>:i+1}</span><div><strong>{title}</strong><p>{goals[i]}</p><small>รางวัล: {rewards[i]}</small></div>{p.claimed===i&&<button disabled={!ready} onClick={()=>dispatch({type:'industry-claim'})}>รับรางวัล</button>}</article>)}{p.claimed===3&&<p>ผ่านบทงานช่างแล้ว! เก็บอิฐเตรียมพัฒนาเมือง บทยุคโลหะยังไม่เปิดในเวอร์ชันนี้</p>}
 {p.task&&<div role="status" className="auto-build-status">กำลังผลิต{p.task.kind==='charcoal'?'ถ่าน':'อิฐ'} · เหลือ {Math.max(0,Math.ceil((p.task.finishAt-now)/1000))} วินาที</div>}
 <h3>สูตรแปรรูปที่เตาเผา</h3>{(['charcoal','brick'] as const).map((kind,i)=><button key={kind} className="blueprint" disabled={!has(v,'kiln')||!!v.craft||!!p.task||p.claimed<i+1||p[kind]>38||!canPay(v,i?{clay:4}:{wood:4})||!!i&&p.charcoal<2} onClick={()=>dispatch({type:'industry-start',kind,now:Date.now()})}>{i?<BrickWall/>:<Flame/>}<span><strong>{i?'อิฐ 2 ก้อน':'ถ่านไม้ 2 ชิ้น'}</strong><small>{i?'ดิน 4 + ถ่าน 2 · 120 วินาที':'ไม้ 4 · 60 วินาที'}</small><em>{p.claimed<i+1?'รับรางวัลบทก่อนเพื่อเปิดสูตร':!has(v,'kiln')?'ต้องสร้างเตาเผา':'จองวัสดุเมื่อเริ่ม · ผลิตต่อขณะ AFK'}</em></span></button>)}</section>;
}
