import {useEffect,useState} from 'react';
import {Dialog} from 'radix-ui';
import {Flame,Tent,TreePine,Wheat,Package,Amphora,Plus,Minus,Volume2,VolumeX,BookOpen,Users,FlaskConical,ArrowRight,Settings2,X,Sprout,Hammer} from 'lucide-react';
import {useVillage} from './store';
import {BUILD,BUILDINGS,RESOURCES,LABEL,RECIPES,JOBS,JOB_NAMES,TILES,assigned,housing,foodNeed,goals,canPay,has,type Building,type Cost,type Recipe,type Resource} from './model';
import {setSound,playCue,attachVisibility,setMusic} from '../audio/sound';
import './village.css';
const ICON={fire:Flame,shelter:Tent,kiln:Amphora,farm:Wheat,store:Package,lumber:TreePine};
const costText=(cost:Cost)=>RESOURCES.filter(r=>cost[r]).map(r=>`${LABEL[r]} ${cost[r]}`).join(' · ');
export default function VillageGame({onLab}:{onLab:()=>void}){
 const {v,dispatch,hydrate,restart,storageError}=useVillage();const [tab,setTab]=useState('build'),[tile,setTile]=useState<number|null>(null),[placing,setPlacing]=useState<Building|null>(null),[pair,setPair]=useState<Resource[]>([]),[sound,toggleSound]=useState(false),[music,toggleMusic]=useState(true),[settings,showSettings]=useState(false),[resetConfirm,setResetConfirm]=useState(false),[winShown,showWin]=useState(false);
 useEffect(()=>{hydrate();return attachVisibility();},[hydrate]);
 useEffect(()=>useVillage.subscribe((next,prev)=>{if(next.v.won&&!prev.v.won){playCue('level');showWin(true);}else if(next.v.known.length>prev.v.known.length||next.v.plots.filter(Boolean).length>prev.v.plots.filter(Boolean).length)playCue('success');}),[]);
 const selected=tile!==null?v.plots[tile]:null;const target=goals(v);const ready=target.every(g=>g.met);
 function choosePlot(i:number){setTile(i);if(placing){dispatch({type:'build',building:placing,tile:i});if(useVillage.getState().v.plots[i]===placing)setPlacing(null);}else if(v.plots[i])setTab('object');}
 const hint=!has(v,'fire')?'ลองไม้ + หิน เพื่อค้นพบกองไฟ':housing(v)<5?'ทดลองไม้ + ไม้ แล้วสร้างเพิงพักเพิ่ม':v.people<5?'รับผู้ตั้งถิ่นฐานเพิ่ม แล้วแบ่งงานหาอาหาร':v.stock.food<20?'สะสมอาหาร 20: เพิ่มคนหาอาหารหรือสร้างแปลงเพาะปลูก':v.stock.wood<8?'จัดคนตัดไม้ให้มีไม้สำรอง 8':'พร้อมแล้ว! กดเตรียมรับฤดูหนาว';
 return <div className="village-shell"><header className="village-header"><span className="village-brand"><Sprout size={25}/> PAPERBOUND <small>หมู่บ้านริมธาร · v0.6</small></span><span>วันที่ {v.day}</span><button className="icon-button" aria-label={sound?'ปิดเสียง':'เปิดเสียง'} onClick={async()=>toggleSound(await setSound(!sound))}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button className="icon-button" aria-label="ตั้งค่า" onClick={()=>showSettings(true)}><Settings2 size={20}/></button></header>
 <div className="resource-bar" aria-label="ทรัพยากร">{RESOURCES.map(r=><span key={r}><small>{LABEL[r]}</small><b key={v.stock[r]}>{v.stock[r]}</b></span>)}<span><small>คน / ที่พัก</small><b>{v.people} / {housing(v)}</b></span></div>
 <main className="village-main"><section className="settlement"><div className="mission-heading"><small>ภารกิจแรก · เตรียมหมู่บ้านก่อนฤดูหนาว</small><h1>{v.won?'โลกเล็ก ๆ ที่คุณสร้างเอง':'จากกองไฟ สู่บ้านของเรา'}</h1><div className="goal-chips">{target.map(g=><span key={g.name} className={g.met?'complete':''}>{g.met?'✓':'○'} {g.name}</span>)}</div></div>
 <div className="world-map"><div className="river-ribbon"/><div className="village-plots" aria-label="พื้นที่วางอาคาร">{v.plots.map((b,i)=>{const Icon=b?ICON[b]:null;const terrain=TILES[i];const compatible=placing&&(!BUILD[placing].terrain||BUILD[placing].terrain===terrain)&&!b;return <button key={i} className={`plot ${terrain} ${b?'built':''} ${tile===i?'selected':''} ${compatible?'can-place':''}`} aria-label={`พื้นที่ ${i+1} ${terrain==='forest'?'ใกล้ป่า':terrain==='river'?'ริมน้ำ':'ทุ่งหญ้า'} ${b?BUILD[b].name:'ว่าง'}`} onClick={()=>choosePlot(i)}>{Icon?<><Icon className={`building-icon ${b}`} size={42}/><span>{BUILD[b!].name}</span>{b==='fire'&&<i className="smoke"/>}</>:<><span className="terrain-mark">{terrain==='forest'?'♧':terrain==='river'?'≈':'·'}</span><small>{compatible?'＋ วางที่นี่':terrain==='forest'?'ใกล้ป่า':terrain==='river'?'ริมน้ำ':'พื้นที่ว่าง'}</small></>}{b==='farm'&&v.jobs.farm>0&&<i className="working-dot"/>}{b==='lumber'&&v.jobs.wood>0&&<i className="working-dot"/>}</button>;})}</div></div>
 <div className="world-instruction">{placing?<><span>กำลังวาง {BUILD[placing].name} · เลือกพื้นที่{BUILD[placing].terrain==='river'?'ริมน้ำ':BUILD[placing].terrain==='forest'?'ใกล้ป่า':'ว่าง'}</span><button onClick={()=>setPlacing(null)}>ยกเลิก</button></>:<span>แตะอาคารเพื่อใช้งาน · {v.plots.filter(Boolean).length}/12 พื้นที่</span>}</div><div className="villager-strip">{Array.from({length:v.people},(_,i)=><span key={i} className={i<assigned(v)?'worker busy':'worker'}><Users size={15}/>{i<assigned(v)?'ทำงาน':'ว่าง'}</span>)}</div>
 <div className="next-step"><span>{v.won?'เล่นต่อแบบอิสระได้เลย ไม่มีเวลารอระหว่างปิดเกม':hint}</span>{ready&&!v.won&&<button onClick={()=>dispatch({type:'winter'})}>พร้อมรับฤดูหนาว ✦</button>}</div></section>
 <section className="village-controls"><div className="village-tabs" role="tablist" aria-label="งานในหมู่บ้าน">{[['build','สร้าง',Hammer],['people','คน',Users],['discover','ทดลอง',FlaskConical],['notes','สูตร',BookOpen]].map(([id,label,I])=>{const Icon=I as typeof Hammer;return <button role="tab" aria-selected={tab===id} key={String(id)} onClick={()=>setTab(String(id))}><Icon size={17}/>{String(label)}</button>;})}</div><div className="village-control-scroll">
 {tab==='build'&&<><h2>สร้างสิ่งที่หมู่บ้านต้องการ</h2><p>ค้นพบสูตรก่อน แล้วใช้ทรัพยากรสร้างของจริง</p><div className="blueprints">{BUILDINGS.map(b=>{const d=BUILD[b],Icon=ICON[b],known=!d.recipe||v.known.includes(d.recipe);return <button key={b} className="blueprint" onClick={()=>{if(!known){setTab('discover');setPair([...RECIPES[d.recipe!].pair] as Resource[]);}else{setPlacing(b);setTile(null);}}}><Icon size={27}/><span><strong>{d.name}</strong><small>{d.effect}</small><em>{known?costText(d.cost):'ยังไม่รู้สูตร · แตะเพื่อทดลอง'}</em></span><b>{known?'＋':'?'}</b></button>;})}</div></>}
 {tab==='people'&&<><h2>แบ่งงานให้ทุกคน</h2><p>คนว่าง {v.people-assigned(v)} · ใช้อาหาร {foodNeed(v)} ต่อวัน</p>{JOBS.map(j=><div className="job-row" key={j}><span>{JOB_NAMES[j]}<small>{j==='forage'?'อาหาร +3':j==='wood'?`ไม้ +${2+Number(v.axe)+Number(has(v,'lumber'))}`:j==='stone'?'หิน +2':j==='clay'?'ดิน +2':j==='water'?`น้ำ +${3+Number(v.pots)}`:'น้ำ −2 → อาหาร +6 / แปลง'}</small></span><button className="icon-button" aria-label={`ลดคน${JOB_NAMES[j]}`} disabled={!v.jobs[j]} onClick={()=>dispatch({type:'assign',job:j,delta:-1})}><Minus size={16}/></button><b>{v.jobs[j]}</b><button className="icon-button" aria-label={`เพิ่มคน${JOB_NAMES[j]}`} disabled={assigned(v)>=v.people||j==='farm'&&v.jobs.farm>=v.plots.filter(b=>b==='farm').length} onClick={()=>dispatch({type:'assign',job:j,delta:1})}><Plus size={16}/></button></div>)}<button className="village-primary" disabled={v.people>=5} onClick={()=>dispatch({type:'recruit'})}>รับผู้ตั้งถิ่นฐาน · อาหาร 4</button><p>{housing(v)<=v.people?'ต้องมีเพิงพักว่างก่อนรับคนเพิ่ม':'รับคนแล้วอย่าลืมจัดงานให้เขา'}</p></>}
 {tab==='discover'&&<><h2>ความรู้ใหม่ มีไว้ใช้งาน</h2><p>ทดลองสำเร็จใช้วัสดุอย่างละ 1 คู่ที่ไม่มีสูตรใหม่ไม่เสียของ สูตรเก็บถาวร ไม่เพิ่มของซ้ำในคลัง</p><div className="experiment-pair">{[0,1].map(i=><button key={i} onClick={()=>setPair(pair.filter((_,n)=>n!==i))}>{pair[i]?LABEL[pair[i]]:'+ วัสดุ'}</button>)}</div><div className="material-picks">{RESOURCES.map(r=><button key={r} onClick={()=>{setPair(pair.length<2?[...pair,r]:[r]);playCue('pick');}}>{LABEL[r]} <small>{v.stock[r]}</small></button>)}</div><button className="village-primary" disabled={pair.length!==2} onClick={()=>{dispatch({type:'experiment',a:pair[0],b:pair[1]});setPair([]);}}>ทดลองค้นพบ ✦</button><h3>เครื่องมือที่ติดตั้งให้หมู่บ้าน</h3>{(['axe','pottery'] as const).map(k=><button className="blueprint" key={k} disabled={k==='axe'?v.axe:v.pots} onClick={()=>dispatch({type:'produce',item:k})}><span><strong>{RECIPES[k].name} {(k==='axe'?v.axe:v.pots)?'✓ ติดตั้งแล้ว':''}</strong><small>{k==='axe'?'เพิ่มผลผลิตไม้ +1 ต่อคน':'ต้องมีเตาเผา · เพิ่มผลผลิตน้ำและเปิดคลังเสบียง'}</small><em>{costText(RECIPES[k].cost)}</em></span></button>)}</>}
 {tab==='notes'&&<><h2>สมุดสูตร {v.known.length}/{Object.keys(RECIPES).length}</h2><p>เลือกคำใบ้เพื่อทดลอง สูตรคือความรู้ ไม่ใช่สิ่งของในคลัง</p>{(Object.keys(RECIPES) as Recipe[]).map(k=><button className="blueprint" key={k} onClick={()=>{setTab('discover');setPair([...RECIPES[k].pair] as Resource[]);}}><span><strong>{v.known.includes(k)?'✓':'○'} {RECIPES[k].name}</strong><small>{RECIPES[k].pair.map(r=>LABEL[r as Resource]).join(' + ')}</small><em>{RECIPES[k].why}</em></span></button>)}<h3>บันทึกผลผลิตล่าสุด</h3>{v.log.map((line,i)=><p key={i}>{line}</p>)}</>}
 {tab==='object'&&<>{selected?<><h2>{BUILD[selected].name}</h2><p>{BUILD[selected].effect}</p>{selected==='kiln'&&<button className="village-primary" disabled={v.pots} onClick={()=>dispatch({type:'produce',item:'pottery'})}>{v.pots?'✓ ภาชนะติดตั้งแล้ว':'ผลิตและติดตั้งภาชนะ · ดิน 2 ไม้ 1'}</button>}{selected==='shelter'&&<button className="village-primary" onClick={()=>dispatch({type:'recruit'})}>รับคนใหม่ · อาหาร 4</button>}{['farm','lumber'].includes(selected)&&<button className="village-primary" onClick={()=>setTab('people')}>จัดคนมาทำงาน</button>}<button onClick={()=>{dispatch({type:'demolish',tile:tile!});if(!useVillage.getState().v.plots[tile!])setTab('build');}}>รื้อคืนวัสดุครึ่งหนึ่ง</button><p>ไม่คืนค่าวิจัยหรือของที่ใช้ผลิตแล้ว ย้ายอาคารโดยรื้อและสร้างใหม่</p></>:<p>เลือกอาคารในแผนที่ หรือเปิดแท็บสร้าง</p>}</>}
 </div><div className="day-bench"><p role="status" key={v.message}>{v.message}</p>{storageError&&<small>บันทึกในเบราว์เซอร์ไม่ได้ ความคืบหน้าอาจหายเมื่อปิดเกม</small>}<button className="village-primary" onClick={()=>dispatch({type:'day'})}>จบวัน · รับผลผลิตและกินอาหาร {foodNeed(v)} <ArrowRight size={18}/></button><small>ไม่มีการรอจริง · เป้าหมายเตรียมพร้อมภายใน 12 วัน เล่นต่อได้หากยังไม่ทัน</small></div></section></main>
 <Dialog.Root open={settings} onOpenChange={showSettings}><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet"><div className="sheet-title"><Dialog.Title>โลกของคุณ</Dialog.Title><Dialog.Close className="icon-button" aria-label="ปิด"><X/></Dialog.Close></div><Dialog.Description>โหมดหมู่บ้านยุคหิน · เล่นคนเดียว บันทึกแยกจากห้องทดลองเดิม</Dialog.Description><div className="sheet-body"><p>สร้างที่พัก รับคน 5 คน และสำรองอาหารกับไม้ให้พร้อมฤดูหนาว ไม่มีคนตายหรือทรัพยากรลดขณะปิดเกม</p><label className="check"><input type="checkbox" checked={music} onChange={e=>{toggleMusic(e.target.checked);setMusic(e.target.checked);}}/> เพลงพื้นหลัง</label><button onClick={onLab}>เปิดห้องทดลองเดิม</button><p>การค้นพบเดิมยังอยู่ โหมดนี้เริ่มความรู้และทรัพยากรแยกกัน</p>{!resetConfirm?<button onClick={()=>setResetConfirm(true)}>เริ่มหมู่บ้านใหม่…</button>:<><p>จะลบเฉพาะหมู่บ้านนี้และเริ่มวันแรก</p><button onClick={()=>{restart();showSettings(false);setResetConfirm(false);setTile(null);setPair([]);setPlacing(null);}}>ยืนยันเริ่มใหม่</button><button onClick={()=>setResetConfirm(false)}>ยกเลิก</button></>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={winShown} onOpenChange={showWin}><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet round-sheet"><Dialog.Title>หมู่บ้านพร้อมแล้ว! ✦</Dialog.Title><Dialog.Description>คุณเตรียมที่พัก ผู้คน และเสบียงได้ใน {v.day} วัน ลองเส้นทางอื่นในครั้งหน้า หรือแต่งโลกนี้ต่อได้เลย</Dialog.Description><Dialog.Close className="village-primary">อยู่กับหมู่บ้านต่อ</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
