import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Dialog} from 'radix-ui';
import {Flame,Tent,TreePine,Wheat,Package,Amphora,Plus,Minus,Volume2,VolumeX,BookOpen,Users,FlaskConical,ArrowRight,Settings2,X,Sprout,Hammer,Flower2,Mail} from 'lucide-react';
import {useVillage} from './store';
import {BUILD,BUILDINGS,RESOURCES,LABEL,RECIPES,JOBS,JOB_NAMES,TILES,PRODUCTION_CYCLE_MS,CRAFT_TIME_MS,storageCapacity,assigned,housing,goals,canPay,has,type Building,type Cost,type Recipe,type Resource} from './model';
import {setSound,playCue,attachVisibility,setMusic} from '../audio/sound';
import './village.css';
import {DECORATIONS,buildingStatus,type Decoration} from './model';
import {RequestsPanel,Neighbors,VillageName} from './CozyPanels';
import {ItemArt} from './scene/ItemArt';
import {VisualCard} from './scene/VisualCard';
import type {SceneHandle,ScreenPoint} from './scene/layout';
import {nextGoal,buildReason} from './guidance';
import {WorldActions} from './WorldActions';
import {decorationUnlocked} from './model';
import {LandPanel,NodePanel} from './LandPanel';
const WorldScene=lazy(()=>import('./scene/WorldScene'));
const ICON={fire:Flame,shelter:Tent,kiln:Amphora,farm:Wheat,store:Package,lumber:TreePine};
const costText=(cost:Cost)=>RESOURCES.filter(r=>cost[r]).map(r=>`${LABEL[r]} ${cost[r]}`).join(' · ');
export default function VillageGame({onLab}:{onLab:()=>void}){
 const [nodeId,setNodeId]=useState<string|null>(null);
 const scene=useRef<SceneHandle|null>(null);
 const {v,dispatch,hydrate,restart,storageError,saveNote,blocked,reloadSave}=useVillage();const [tab,setTab]=useState('build'),[quick,setQuick]=useState(false),[discovery,setDiscovery]=useState<Recipe|null>(null),[buildFilter,setBuildFilter]=useState<'all'|'ready'>('all'),[tile,setTile]=useState<number|null>(null),[placing,setPlacing]=useState<Building|null>(null),[pair,setPair]=useState<Resource[]>([]),[sound,toggleSound]=useState(false),[music,toggleMusic]=useState(true),[settings,showSettings]=useState(false),[resetConfirm,setResetConfirm]=useState(false),[winShown,showWin]=useState(false),[moving,setMoving]=useState<number|null>(null),[decorating,setDecorating]=useState<Decoration|null>(null),[now,setNow]=useState(Date.now());
 useEffect(()=>{hydrate();const audioCleanup=attachVisibility(),pulse=()=>{const time=Date.now();setNow(time);dispatch({type:'sync',now:time});},clock=setInterval(()=>setNow(Date.now()),1000),production=setInterval(pulse,5000),visible=()=>{if(!document.hidden)pulse();};document.addEventListener('visibilitychange',visible);pulse();return()=>{audioCleanup();clearInterval(clock);clearInterval(production);document.removeEventListener('visibilitychange',visible);};},[hydrate,dispatch]);
 useEffect(()=>useVillage.subscribe((next,prev)=>{if(!next.loaded||!prev.loaded)return;const found=next.v.known.find(k=>!prev.v.known.includes(k));if(found)setDiscovery(found);if(next.v.won&&!prev.v.won){playCue('level');showWin(true);}else if(next.v.completed.length>prev.v.completed.length||next.v.decorations.some((d,i)=>d!==prev.v.decorations[i])||next.v.known.length>prev.v.known.length||next.v.plots.filter(Boolean).length>prev.v.plots.filter(Boolean).length)playCue('success');}),[]);
 useEffect(()=>{if(!discovery)return;const timer=setTimeout(()=>setDiscovery(null),5000);return()=>clearTimeout(timer);},[discovery]);
 const selected=tile!==null?v.plots[tile]:null;const target=goals(v);
 function choosePlot(i:number){setNodeId(null);setTile(i);setQuick(false);if(moving!==null){dispatch({type:'move',from:moving,to:i});if(!useVillage.getState().v.plots[moving]){setMoving(null);setTab('object');}return;}if(decorating){dispatch({type:'decorate',decoration:decorating,tile:i});if(useVillage.getState().v.decorations[i]===decorating){setDecorating(null);setTab('object');}return;}if(placing){dispatch({type:'build',building:placing,tile:i});if(useVillage.getState().v.plots[i]===placing)setPlacing(null);}else if(v.plots[i])setQuick(true);else if(v.decorations[i])setTab('object');else setTab('build');}
 function dropBuilding(b:Building,p:ScreenPoint){const index=scene.current?.tileAt(p);if(index!==undefined&&index!==null){dispatch({type:'build',building:b,tile:index});setTile(index);}setPlacing(null);}
 function dropDecoration(d:Decoration,p:ScreenPoint){const index=scene.current?.tileAt(p);if(index!==undefined&&index!==null){dispatch({type:'decorate',decoration:d,tile:index});setTile(index);}setDecorating(null);}
 const guide=nextGoal(v),displayCarry=(v.productionCarryMs+Math.max(0,now-v.lastActiveAt))%PRODUCTION_CYCLE_MS,cycleLeft=Math.max(0,PRODUCTION_CYCLE_MS-displayCarry),cycleProgress=Math.min(100,displayCarry/PRODUCTION_CYCLE_MS*100),craftLeft=v.craft?Math.max(0,v.craft.finishAt-now):0,craftProgress=v.craft?Math.min(100,(now-v.craft.startedAt)/CRAFT_TIME_MS*100):0;
 function openRecipe(r:Recipe){setQuick(false);setTab('discover');setPair([...RECIPES[r].pair] as Resource[]);}
 function followGoal(){setQuick(false);if(guide.celebrate){dispatch({type:'winter'});return;}if(guide.recipe){openRecipe(guide.recipe);return;}if(guide.art==='pottery'&&v.known.includes('pottery')){const i=v.plots.indexOf('kiln');if(i>=0){setTile(i);setQuick(true);return;}}setTab(guide.tab);setBuildFilter('all');if(guide.building&&guide.tab==='build'){setPlacing(guide.building);setMoving(null);setDecorating(null);setTile(null);}}

 return <div className="village-shell"><header className="village-header"><span className="village-brand"><Sprout size={25}/> PAPERBOUND <small>โลกที่ค่อย ๆ กว้างขึ้น · v0.11</small></span><span>ยุคหิน</span><button className="icon-button" aria-label={sound?'ปิดเสียง':'เปิดเสียง'} onClick={async()=>toggleSound(await setSound(!sound))}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button className="icon-button" aria-label="ตั้งค่า" onClick={()=>showSettings(true)}><Settings2 size={20}/></button></header>
 <div className="resource-bar" aria-label="ทรัพยากร">{RESOURCES.map(r=><button key={r} aria-label={`${LABEL[r]} ${v.stock[r]} เลือกทดลอง`} onClick={()=>{setTab('discover');setPair(pair.length<2?[...pair,r]:[r]);}}><ItemArt kind={r}/><span><small>{LABEL[r]}</small><b key={v.stock[r]}>{v.stock[r]}</b></span></button>)}<span><small>คน / ที่พัก</small><b>{v.people} / {housing(v)}</b></span></div>
 <main className="village-main"><section className="settlement"><div className="mission-heading"><div><small>{v.won?'บ้านของเรา · เติบโตต่อได้':'บทที่ 1 · บ้านสำหรับทุกคน'}</small><h1 className="village-display-name" title={v.name}>{v.name}</h1></div><span className="chapter-count" aria-label={`เป้าหมายสำเร็จ ${target.filter(g=>g.met).length} จาก ${target.length}`}>{v.won?'✦':`${target.filter(g=>g.met).length}/${target.length}`}</span></div>
 <div className="world-map">{discovery&&<div className="discovery-toast" role="status"><ItemArt kind={discovery}/><span><small>ค้นพบแล้ว!</small><strong>{RECIPES[discovery].name}</strong></span><button className="icon-button" aria-label="ปิดการแจ้งค้นพบ" onClick={()=>setDiscovery(null)}><X size={16}/></button></div>}<Suspense fallback={<div className="world-loading">กำลังเปิดโลกของเรา…</div>}><WorldScene onNode={id=>{setNodeId(id);setQuick(false);setTile(null);setPlacing(null);setDecorating(null);setMoving(null);}} v={v} selected={tile} placing={placing} decorating={decorating} moving={moving} onChoose={choosePlot} onPeople={()=>{setQuick(false);setTab('people');}} onMove={(from,to)=>{dispatch({type:'move',from,to});setTile(useVillage.getState().v.plots[to]?to:from);setTab('object');setMoving(null);}} handle={scene}/></Suspense>{nodeId&&v.nodes.some(n=>n.id===nodeId)&&<NodePanel v={v} node={v.nodes.find(n=>n.id===nodeId)!} now={now} dispatch={dispatch} onClose={()=>setNodeId(null)}/ >}{quick&&tile!==null&&selected&&!placing&&!decorating&&moving===null&&<WorldActions v={v} tile={tile} dispatch={dispatch} onTab={t=>{setQuick(false);setTab(t);}} onRecipe={openRecipe} onMove={()=>{setQuick(false);setMoving(tile);setPlacing(null);setDecorating(null);}} onClose={()=>{setQuick(false);setTile(null);}}/>}</div>
 <div className="world-instruction">{moving!==null?<><span>ย้ายฟรี · เลือกพื้นที่ว่างที่เหมาะกับอาคาร</span><button onClick={()=>setMoving(null)}>ยกเลิก</button></>:decorating?<><span>วาง{DECORATIONS[decorating].name} · เลือกพื้นที่ รวมหน้าบ้านได้</span><button onClick={()=>setDecorating(null)}>ยกเลิก</button></>:placing?<><span>กำลังวาง {BUILD[placing].name} · เลือกพื้นที่{BUILD[placing].terrain==='river'?'ริมน้ำ':BUILD[placing].terrain==='forest'?'ใกล้ป่า':'ว่าง'}</span><button onClick={()=>setPlacing(null)}>ยกเลิก</button></>:<span>แตะวัตถุเพื่อใช้งาน · ลากอาคารเพื่อย้าย · {v.plots.filter(Boolean).length}/{v.plots.length} พื้นที่</span>}</div><div className="villager-strip">{Array.from({length:v.people},(_,i)=><span key={i} className={i<assigned(v)?'worker busy':'worker'}><Users size={15}/>{v.names[i]}</span>)}</div>
 <button className="next-goal" onClick={followGoal}><ItemArt kind={guide.art}/><span><strong>{guide.title}</strong><small>{guide.detail}</small></span><b>{guide.label} <ArrowRight size={15}/></b></button></section>
 <section className="village-controls"><div className="village-tabs" aria-label="งานในหมู่บ้าน">{[['land','พื้นที่',Sprout],['build','สร้าง',Hammer],['people','คน',Users],['discover','ทดลอง',FlaskConical],['notes','สูตร',BookOpen],['decorate','แต่งบ้าน',Flower2],['requests','คำขอ',Mail]].map(([id,label,I])=>{const Icon=I as typeof Hammer;return <button aria-pressed={tab===id} key={String(id)} onClick={()=>{setQuick(false);setNodeId(null);setTab(String(id));}}><Icon size={17}/>{String(label)}</button>;})}</div><div className="village-control-scroll">
 {tab==='land'&&<LandPanel v={v} dispatch={dispatch}/>}
 {tab==='decorate'&&<><h2>ของแต่งชิ้นเล็ก ๆ</h2><p>ลากภาพจากจุดจับไปวางในฉาก หรือแตะเพื่อเลือก</p><div className="visual-card-grid">{(Object.keys(DECORATIONS) as Decoration[]).map(d=><VisualCard key={d} kind={d} name={DECORATIONS[d].name} cost={decorationUnlocked(v,d)?costText(DECORATIONS[d].cost):'ทำคำขอเพื่อนบ้านเพื่อเปิด'} locked={!decorationUnlocked(v,d)} onSelect={()=>{if(decorationUnlocked(v,d)){setDecorating(d);setPlacing(null);setMoving(null);}else setTab('requests');}} onDragStart={()=>{setDecorating(d);setPlacing(null);setMoving(null);}} onDrop={p=>dropDecoration(d,p)}/>)}</div></>}
 {tab==='requests'&&<RequestsPanel/>}
 {tab==='build'&&<><h2>สร้างโลกของเรา</h2><p>ลากการ์ดภาพไปวางบนพื้นเรืองแสง · หรือแตะการ์ดแล้วเลือกจุดวาง</p><div className="card-filters" aria-label="กรองแบบก่อสร้าง"><button aria-pressed={buildFilter==='all'} onClick={()=>setBuildFilter('all')}>ทั้งหมด</button><button aria-pressed={buildFilter==='ready'} onClick={()=>setBuildFilter('ready')}>สร้างได้ตอนนี้ · {BUILDINGS.filter(b=>!buildReason(v,b)).length}</button></div>{buildFilter==='ready'&&!BUILDINGS.some(b=>!buildReason(v,b))&&<p>ยังไม่มีแบบที่พร้อม ลองดูทั้งหมดเพื่อเรียนรู้สูตรหรือจัดหาวัสดุ</p>}<div className="visual-card-grid">{BUILDINGS.filter(b=>buildFilter==='all'||!buildReason(v,b)).map(b=>{const d=BUILD[b],known=!d.recipe||v.known.includes(d.recipe);return <VisualCard key={b} kind={b} name={d.name} cost={buildReason(v,b)??costText(d.cost)} locked={!known} onSelect={()=>{if(!known){setTab('discover');setPair([...RECIPES[d.recipe!].pair] as Resource[]);}else{setPlacing(b);setMoving(null);setDecorating(null);setTile(null);}}} onDragStart={()=>{setPlacing(b);setMoving(null);setDecorating(null);}} onDrop={p=>dropBuilding(b,p)}/>;})}</div></>}
 {tab==='people'&&<><Neighbors/><h2>แบ่งงานให้ทุกคน</h2><p>คนว่าง {v.people-assigned(v)} · ทุกงานส่งผลผลิตเข้าคลังทุก 30 วินาที แม้พักเกม</p>{JOBS.map(j=><div className="job-row" key={j}><ItemArt kind={j==='forage'?'food':j==='farm'?'farm':j}/><span>{JOB_NAMES[j]}<small>{j==='forage'?'อาหาร +3 / รอบ':j==='wood'?`ไม้ +${2+Number(v.axe)+Number(has(v,'lumber'))} / รอบ`:j==='stone'?'หิน +2 / รอบ':j==='clay'?'ดิน +2 / รอบ':j==='water'?`น้ำ +${3+Number(v.pots)} / รอบ`:'น้ำ −2 → อาหาร +6 / รอบ / แปลง'}</small></span><button className="icon-button" aria-label={`ลดคน${JOB_NAMES[j]}`} disabled={!v.jobs[j]} onClick={()=>dispatch({type:'assign',job:j,delta:-1})}><Minus size={16}/></button><b>{v.jobs[j]}</b><button className="icon-button" aria-label={`เพิ่มคน${JOB_NAMES[j]}`} disabled={assigned(v)>=v.people||j==='farm'&&v.jobs.farm>=v.plots.filter(b=>b==='farm').length} onClick={()=>dispatch({type:'assign',job:j,delta:1})}><Plus size={16}/></button></div>)}<button className="village-primary" disabled={v.people>=5||housing(v)<=v.people||!canPay(v,{food:4})} onClick={()=>dispatch({type:'recruit'})}>รับผู้ตั้งถิ่นฐาน · อาหาร 4</button><p>{housing(v)<=v.people?'ต้องมีเพิงพักว่างก่อนรับคนเพิ่ม':'รับคนแล้วอย่าลืมจัดงานให้เขา'}</p></>}
 {tab==='discover'&&<><h2>ความรู้ใหม่ มีไว้ใช้งาน</h2><p>การทดลองคือ puzzle หลัก สูตรที่รู้แล้วจึงสั่งผลิตได้ วัตถุดิบจะถูกจองเมื่อเริ่มคิว</p><div className="experiment-pair">{[0,1].map(i=><button key={i} data-experiment-slot={i} aria-label={`ช่องทดลอง ${i+1}`} onClick={()=>setPair(pair.filter((_,n)=>n!==i))}>{pair[i]?<><ItemArt kind={pair[i]}/><small>{LABEL[pair[i]]}</small></>:'+ วัสดุ'}</button>)}</div><div className="visual-card-grid material-cards">{RESOURCES.map(r=><VisualCard key={r} kind={r} name={LABEL[r]} cost={`${v.stock[r]} ชิ้น`} onSelect={()=>{setPair(pair.length<2?[...pair,r]:[r]);playCue('pick');}} onDrop={p=>{const slot=document.elementsFromPoint(p.x,p.y).find(e=>e.hasAttribute('data-experiment-slot'));if(slot){const index=Number(slot.getAttribute('data-experiment-slot'));setPair(old=>index===0?[r,...old.slice(1)]:old.length?[old[0],r]:[r]);playCue('pick');}}}/>)}</div><button className="village-primary" disabled={pair.length!==2} onClick={()=>{dispatch({type:'experiment',a:pair[0],b:pair[1]});setPair([]);}}>ทดลองค้นพบ ✦</button><h3>เครื่องมือที่ติดตั้งให้หมู่บ้าน</h3>{(['axe','pottery'] as const).map(k=><button className="blueprint" key={k} disabled={!!v.craft||(k==='axe'?v.axe:v.pots)} onClick={()=>dispatch({type:'queue-craft',item:k,now:Date.now()})}><ItemArt kind={k}/><span><strong>{RECIPES[k].name} {(k==='axe'?v.axe:v.pots)?'✓ ติดตั้งแล้ว':v.craft?.item===k?'· กำลังผลิต':''}</strong><small>{k==='axe'?'เพิ่มผลผลิตไม้ +1 ต่อคน':'ต้องมีเตาเผา · เพิ่มผลผลิตน้ำและเปิดคลังเสบียง'}</small><em>{v.craft?.item===k?`เหลือ ${Math.ceil(craftLeft/1000)} วินาที`:costText(RECIPES[k].cost)+' · 90 วินาที'}</em></span></button>)}</>}
 {tab==='notes'&&<><h2>สมุดสูตร {v.known.length}/{Object.keys(RECIPES).length}</h2><p>เลือกคำใบ้เพื่อทดลอง สูตรคือความรู้ ไม่ใช่สิ่งของในคลัง</p>{(Object.keys(RECIPES) as Recipe[]).map(k=><button className="blueprint" key={k} onClick={()=>{setTab('discover');setPair([...RECIPES[k].pair] as Resource[]);}}><ItemArt kind={k}/><span><strong>{v.known.includes(k)?'✓':'○'} {RECIPES[k].name}</strong><small>{RECIPES[k].pair.map(r=>LABEL[r as Resource]).join(' + ')}</small><em>{RECIPES[k].why}</em></span></button>)}<h3>บันทึกผลผลิตล่าสุด</h3>{v.log.map((line,i)=><p key={i}>{line}</p>)}</>}
 {tab==='object'&&<>{selected?<><div className="object-portrait"><ItemArt kind={selected}/><h2>{BUILD[selected].name}</h2></div><p>{BUILD[selected].effect}</p><div className="object-status">{buildingStatus(v,selected,tile!).label}<button onClick={()=>setTab(buildingStatus(v,selected,tile!).tab)}>ดูงานที่เกี่ยวข้อง →</button></div><button className="village-primary" onClick={()=>{setMoving(tile);setPlacing(null);setDecorating(null);}}>ย้ายอาคารฟรี</button>{selected==='kiln'&&<button className="village-primary" disabled={v.pots||!!v.craft} onClick={()=>dispatch({type:'queue-craft',item:'pottery',now:Date.now()})}>{v.pots?'✓ ภาชนะติดตั้งแล้ว':v.craft?'โต๊ะงานกำลังผลิต':'เข้าคิวภาชนะ · 90 วินาที'}</button>}{selected==='shelter'&&<button className="village-primary" onClick={()=>dispatch({type:'recruit'})}>รับคนใหม่ · อาหาร 4</button>}{['farm','lumber'].includes(selected)&&<button className="village-primary" onClick={()=>setTab('people')}>จัดคนมาทำงาน</button>}<button onClick={()=>{dispatch({type:'demolish',tile:tile!});if(!useVillage.getState().v.plots[tile!])setTab('build');}}>รื้อคืนวัสดุครึ่งหนึ่ง</button><p>รื้อคืนวัสดุครึ่งหนึ่ง หากแค่อยากจัดหมู่บ้านใหม่ ใช้ย้ายฟรีได้เลย</p></>:<p>พื้นที่ตกแต่งของเรา</p>}{tile!==null&&v.decorations[tile]&&<div className="object-decoration"><ItemArt kind={v.decorations[tile]!}/><h3>{DECORATIONS[v.decorations[tile]!].name}</h3><p>ของตกแต่งอยู่กับพื้นที่ ย้ายอาคารแล้วของแต่งยังอยู่ที่เดิม</p><button onClick={()=>dispatch({type:'remove-decoration',tile})}>เก็บของแต่ง · คืนวัสดุเต็มจำนวน</button></div>}</>}
 </div><div className="day-bench"><div className="production-status" aria-label={`ผลผลิตรอบถัดไปใน ${Math.ceil(cycleLeft/1000)} วินาที`}><div className="production-copy"><strong>สถานีกำลังทำงาน</strong><small>รอบถัดไป {Math.ceil(cycleLeft/1000)} วิ · คลัง {Math.max(...RESOURCES.map(r=>v.stock[r]))}/{storageCapacity(v)}</small></div><div className="progress-track"><i style={{width:`${cycleProgress}%`}}/></div></div>
{v.craft&&<div className="craft-progress"><ItemArt kind={v.craft.item}/><span><strong>กำลังทำ {RECIPES[v.craft.item].name}</strong><small>เหลือ {Math.ceil(craftLeft/1000)} วินาที</small><i style={{width:`${craftProgress}%`}}/></span></div>}
{v.awayReport&&<button className="away-report" onClick={()=>dispatch({type:'clear-away'})}><span>กลับมาแล้ว ✦</span><small>{v.awayReport}</small><b>รับทราบ</b></button>}
<p role="status" key={v.message}>{v.message}</p><small className={storageError?'save-warning':'save-status'} role="status">{saveNote}</small>{blocked&&<button onClick={reloadSave}>โหลดเซฟล่าสุด</button>}
<small>รับของอัตโนมัติ · พักเกมได้สูงสุด 4 ชั่วโมง · ไม่มีคนตายระหว่างพัก</small></div></section></main>
 <Dialog.Root open={settings} onOpenChange={showSettings}><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet"><div className="sheet-title"><Dialog.Title>โลกของคุณ</Dialog.Title><Dialog.Close className="icon-button" aria-label="ปิด"><X/></Dialog.Close></div><Dialog.Description>โหมดหมู่บ้านยุคหิน · ผลิตตามเวลาจริงและเล่นต่อระหว่างพัก</Dialog.Description><div className="sheet-body"><VillageName key={v.name}/><p>จัดคนให้เหมาะกับสิ่งที่อยากสร้าง ผลผลิตเข้าคลังทุก 30 วินาที และคำนวณย้อนหลังสูงสุด 4 ชั่วโมง คลังเต็มแล้วสถานีจะหยุดเอง</p><p className="account-note">เล่นแบบแขก · เซฟอยู่ในเบราว์เซอร์นี้เท่านั้น บัญชี Google/อีเมลและการเล่นข้ามอุปกรณ์ยังไม่เปิดใช้</p><label className="check"><input type="checkbox" checked={music} onChange={e=>{toggleMusic(e.target.checked);setMusic(e.target.checked);}}/> เพลงพื้นหลัง</label><button onClick={onLab}>เปิดห้องทดลองเดิม</button><p>การค้นพบเดิมยังอยู่ โหมดนี้เริ่มความรู้และทรัพยากรแยกกัน</p>{!resetConfirm?<button onClick={()=>setResetConfirm(true)}>เริ่มหมู่บ้านใหม่…</button>:<><p>จะลบเฉพาะหมู่บ้านนี้และเริ่มวันแรก</p><button onClick={()=>{restart();showSettings(false);setResetConfirm(false);setTile(null);setNodeId(null);setPair([]);setPlacing(null);setMoving(null);setDecorating(null);}}>ยืนยันเริ่มใหม่</button><button onClick={()=>setResetConfirm(false)}>ยกเลิก</button></>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={winShown} onOpenChange={showWin}><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet round-sheet"><Dialog.Title>งานเลี้ยงของเราเริ่มแล้ว! ✦</Dialog.Title><Dialog.Description>เพื่อนบ้านทั้ง {v.people} คนมารวมตัวกันที่ {v.name} ขอบคุณที่สร้างบ้านหลังนี้ จะทำคำขอหรือแต่งหมู่บ้านต่อก็ได้เลย</Dialog.Description><Dialog.Close className="village-primary">อยู่กับหมู่บ้านต่อ</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
