'use client';
import {Dialog} from 'radix-ui';
import {cardName,tags as tagNames,weather,innovations,feedbackText} from '@/i18n/th';
import {deriveCity} from '@/civilization/model';
import {playCue,setSound,setMusic,setVolume,attachVisibility} from '@/audio/sound';
import {memo,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import * as Icons from 'lucide-react';
import {useGame,available,context} from '@/game/store';
import {Card,nextHint,DATA,knowledge,advanceRequirements} from '@/game/engine';
import {indexCards,filterCards,pageCards} from '@/game/collection';
import {newPartners} from '@/game/research';
import {CivilizationView} from '@/components/CivilizationView';
import {ResearchPanel} from '@/components/ResearchPanel';
import artManifest from '@/data/art-manifest.json';
function Glyph({name,size=30}:{name:string;size?:number}){const glyphs:Record<string,React.ComponentType<{size:number;strokeWidth:number}>>={Amphora:Icons.Amphora,Axe:Icons.Axe,BrickWall:Icons.BrickWall,Car:Icons.Car,Castle:Icons.Castle,CircleDot:Icons.CircleDot,Cloud:Icons.Cloud,Coffee:Icons.Coffee,Cog:Icons.Cog,Compass:Icons.Compass,Diamond:Icons.Diamond,Tent:Icons.Tent,ShoppingBasket:Icons.ShoppingBasket,Droplets:Icons.Droplets,Flame:Icons.Flame,Flower2:Icons.Flower2,Gem:Icons.Gem,GraduationCap:Icons.GraduationCap,Hammer:Icons.Hammer,Hexagon:Icons.Hexagon,House:Icons.House,Layers:Icons.Layers,Leaf:Icons.Leaf,Map:Icons.Map,Mountain:Icons.Mountain,Rainbow:Icons.Rainbow,Sailboat:Icons.Sailboat,ScanEye:Icons.ScanEye,Scroll:Icons.Scroll,Send:Icons.Send,Ship:Icons.Ship,Sprout:Icons.Sprout,Sun:Icons.Sun,Telescope:Icons.Telescope,TreePine:Icons.TreePine,Trees:Icons.Trees,Waves:Icons.Waves,Wheat:Icons.Wheat,Wind:Icons.Wind};const Icon=glyphs[name]??Icons.Sparkles;return <Icon size={size} strokeWidth={1.6}/>;}
const Tile=memo(function Tile({card,onPick,visual,highlight,favorite,onFavorite}:{card:Card;onPick:(c:Card,index?:number)=>void;visual:boolean;highlight:boolean;favorite:boolean;onFavorite:(id:string)=>void}){
 const [artFailed,setArtFailed]=useState(false); const art=(artManifest.assets as Record<string,{src:string;alt:string}>)[card.artKey];
 const el=useRef<HTMLButtonElement>(null),ghost=useRef<HTMLElement|null>(null),frame=useRef(0);
 const start=useRef<{x:number;y:number;drag:boolean}|null>(null),suppress=useRef(false);
 function clean(){cancelAnimationFrame(frame.current);ghost.current?.remove();ghost.current=null;start.current=null;document.querySelectorAll('[data-ingredient-slot]').forEach(n=>n.classList.remove('drop-active'));}
 useEffect(()=>()=>clean(),[]);
 return <div className="tile-wrap"><button className={'favorite-button '+(favorite?'is-favorite':'')} aria-label={(favorite?'เลิกปักหมุด ':'ปักหมุด ')+cardName(card)} aria-pressed={favorite} onClick={()=>onFavorite(card.id)}><Icons.Star size={14} fill={favorite?'currentColor':'none'}/></button><button ref={el} className={'element '+card.tone+(!visual?' words-card':'')+(highlight?' has-new-recipe':'')} title={card.tags.map(t=>tagNames[t]??t).join(' · ')} onContextMenu={e=>e.preventDefault()} onClick={()=>{if(suppress.current){suppress.current=false;return;}onPick(card);}} onPointerDown={e=>{if(e.button!==0)return;if(e.pointerType==='touch'&&!(e.target as HTMLElement).closest('[data-drag-handle]'))return;suppress.current=false;start.current={x:e.clientX,y:e.clientY,drag:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const s=start.current;if(!s)return;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.hypot(dx,dy)>7)s.drag=true;if(s.drag&&el.current){if(!ghost.current){const rect=el.current.getBoundingClientRect(),g=el.current.cloneNode(true) as HTMLElement;g.setAttribute('aria-hidden','true');Object.assign(g.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',zIndex:'1000',pointerEvents:'none',opacity:'.95'});document.body.appendChild(g);ghost.current=g;}cancelAnimationFrame(frame.current);const x=e.clientX,y=e.clientY;frame.current=requestAnimationFrame(()=>{if(ghost.current)ghost.current.style.transform=`translate(${dx}px,${dy}px) rotate(-5deg) scale(1.06)`;const slot=document.elementsFromPoint(x,y).find(n=>n.hasAttribute('data-ingredient-slot'));document.querySelectorAll('[data-ingredient-slot]').forEach(n=>n.classList.toggle('drop-active',n===slot));});}}} onPointerCancel={clean} onPointerUp={e=>{if(start.current?.drag){suppress.current=true;const slot=document.elementsFromPoint(e.clientX,e.clientY).find(x=>x.hasAttribute('data-ingredient-slot'));if(slot)onPick(card,Number(slot.getAttribute('data-ingredient-slot')));}clean();}}><span className="drag-handle" data-drag-handle title="ลากจากตรงนี้"><Icons.Grip size={14}/></span><span className="element-tier">{card.depth===0?'วัสดุ':card.mods?'แนวคิด':`ระดับ ${card.depth}`}</span>{visual&&(art&&!artFailed?<img className="card-art" src={art.src} alt={art.alt} loading="lazy" decoding="async" width="96" height="96" onError={()=>setArtFailed(true)}/>:<Glyph name={card.icon}/>)}<strong>{cardName(card)}</strong><span className="element-tag">{card.tags.slice(0,2).map(t=>tagNames[t]??t).join(" · ")}</span><span className="card-points">{highlight?'✦ มีสูตรใหม่':`${card.depth*10+(card.mods?5:0)} VP`}</span></button></div>;
});
function Sheet({title,children,trigger}:{title:string;children:React.ReactNode;trigger:React.ReactNode}){return <Dialog.Root><Dialog.Trigger asChild>{trigger}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet"><div className="sheet-title"><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="icon-button" aria-label="ปิดหน้าต่าง"><Icons.X size={20}/></Dialog.Close></div><Dialog.Description className="sr-only">ปรับตัวเลือกและกลับไปทดลองต่อได้ทันที</Dialog.Description><div className="sheet-body">{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>}
export default function Page(){
 const s=useGame();const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[tag,setTag]=useState('all'),[eraFilter,setEraFilter]=useState('all'),[tier,setTier]=useState('all'),[sort,setSort]=useState('recent'),[page,setPage]=useState(0),[visual,setVisual]=useState(false),[now,setNow]=useState(Date.now()),[hint,setHint]=useState(''),[sound,setSoundState]=useState(false),[music,setMusicState]=useState(true),[volume,setVolumeState]=useState(.35),[notice,setNotice]=useState<{id:number;text:string;level:boolean}|null>(null);
 useEffect(()=>{useGame.getState().hydrate();const detach=attachVisibility();const timer=setInterval(()=>{setNow(Date.now());useGame.getState().tick();if(!document.hidden)useGame.getState().helperTick();},250);return()=>{clearInterval(timer);detach();};},[]);
 useEffect(()=>useGame.subscribe((next,prev)=>{if(next.feedback?.id===prev.feedback?.id||!next.feedback)return;const f=next.feedback;if(f.kind==='fail'){playCue('fail');setNotice({id:f.id,text:'ยังไม่ลงตัว… ลองเปลี่ยนวัสดุดูนะ',level:false});return;}const before=deriveCity(available(prev),prev.era,prev.event),after=deriveCity(available(next),next.era,next.event),level=after.stage>before.stage;playCue(level?'level':f.points>0?'points':'success');setNotice({id:f.id,text:`${level?'เมืองเติบโตแล้ว! ':''}${next.last?cardName(next.last.card):'ทดลองสำเร็จ'}${f.points>0?` +${f.points} แต้ม`:' · เคยค้นพบแล้ว'}`,level});}),[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(null),3500);return()=>clearTimeout(t);},[notice]);
 const cards=useMemo(()=>available(s),[s.cards,s.mode,s.discovered,s.era]);const ctx=useMemo(()=>context(s),[s.era,s.event,s.mode,s.cards,s.discovered]);const anchor=s.slots[0]??s.slots[1];const partners=useMemo(()=>newPartners(anchor,cards,ctx),[anchor,cards,ctx]);
 const translated=useMemo(()=>cards.map(c=>({...c,name:cardName(c)+' '+c.name,tags:[...c.tags,...c.tags.map(t=>tagNames[t]??t)]})),[cards]);const index=useMemo(()=>indexCards(translated),[translated]);const byId=useMemo(()=>new Map(cards.map(c=>[c.id,c])),[cards]);
 const shown=useMemo(()=>filterCards(index,query,filter,{tag,era:eraFilter,tier,sort,favorites:s.favorites,partners}),[index,query,filter,tag,eraFilter,tier,sort,s.favorites,partners]);const pages=Math.max(1,Math.ceil(shown.length/48)),current=Math.min(page,pages-1),visible=pageCards(shown,current).map(c=>byId.get(c.id)!);
 useEffect(()=>setPage(0),[query,filter,tag,eraFilter,tier,sort,s.mode,s.scope]);
 const pick=useCallback((c:Card,i?:number)=>{useGame.getState().add(c,i);playCue('pick');},[]);const seconds=Math.max(0,Math.ceil((s.deadline-now)/1000));const requirements=advanceRequirements(ctx.known);const known=knowledge(ctx.known);
 function resetFilters(){setQuery('');setFilter('all');setTag('all');setEraFilter('all');setTier('all');}
 function suggest(){const pair=nextHint(cards,ctx);if(pair){s.clear();s.add(pair[0],0);resetFilters();setFilter('partners');setHint('เลือกการ์ดขอบเรืองแสง เพื่อพบสิ่งที่ยังไม่เคยสร้าง');}else setHint('ลองวิจัยหรือเปิดความรู้ใหม่ เพื่อเพิ่มความเป็นไปได้');}
 async function toggleSound(){const active=await setSound(!sound);setSoundState(active);if(!active&&!sound)setHint('เปิดเสียงไม่ได้ ลองกดอีกครั้งในเบราว์เซอร์ที่รองรับเสียง');}
 return <div className="game-shell"><header className="game-header"><div className="brand"><Icons.Sprout size={25}/><span>PAPERBOUND<small>โลกเล็ก ๆ จากไอเดียของคุณ</small></span></div><div className="header-stats"><span key={s.score} className="score">✦ {s.score}<small> แต้ม</small></span><span className={'clock '+(s.mode==='challenge'&&seconds<10?'urgent':'')}>{s.mode==='sandbox'?<Icons.Infinity size={20}/>:<><Icons.Timer size={16}/>{seconds}วิ</>}</span></div><nav><button className="icon-button" onClick={toggleSound} aria-label={sound?'ปิดเสียง':'เปิดเสียง'} aria-pressed={sound}>{sound?<Icons.Volume2 size={20}/>:<Icons.VolumeX size={20}/>}</button><Sheet title="ตั้งค่าโลกของเรา" trigger={<button className="icon-button" aria-label="ตั้งค่า"><Icons.Settings2 size={20}/></button>}><p>ต้นแบบเล่นคนเดียว · บันทึกในเบราว์เซอร์นี้</p><label>ขอบเขตยุค<select value={s.scope} onChange={e=>s.setScope(e.target.value as 'stone'|'journey')}><option value="stone">ยุคหินเท่านั้น</option><option value="journey">เดินทางสู่ยุคสำริด</option></select></label><label>สภาพแวดล้อม<select value={s.event} disabled={s.mode==='challenge'} onChange={e=>s.setEvent(e.target.value)}>{DATA.events.map(e=><option key={e.id} value={e.id}>{weather[e.id]}</option>)}</select></label><p>{s.event==='cold'?'อากาศหนาว: ต้องรู้จักไฟก่อนเพาะปลูก':s.event==='rain'?'ฤดูฝน: การค้นพบบางคุณสมบัติได้แต้มพิเศษ':'ฟ้าใส: เหมาะกับการทดลองอย่างอิสระ'}</p><div className="button-row"><button onClick={()=>s.start('sandbox')} aria-pressed={s.mode==='sandbox'}>เล่นอิสระ</button><button onClick={()=>s.start('challenge')} aria-pressed={s.mode==='challenge'}>เริ่มจับเวลา 3 × 45 วิ</button></div><p>เริ่มโหมดใหม่จะรีเซ็ตแต้มรอบเล่น คอลเลกชันเดิมยังอยู่</p><label className="check"><input type="checkbox" checked={visual} onChange={e=>setVisual(e.target.checked)}/> แสดงไอคอนการ์ด</label><label className="check"><input type="checkbox" checked={music} onChange={e=>{setMusicState(e.target.checked);setMusic(e.target.checked);}}/> เพลงบรรยากาศ (เปิดเสียงที่แถบบนก่อน)</label><label>ระดับเสียง<input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>{setVolumeState(+e.target.value);setVolume(+e.target.value);}}/></label><p>เมืองเติบโตจาก XP ของการ์ดใหม่และเงื่อนไขการค้นพบ สร้างซ้ำไม่เพิ่ม XP แนวคิดจากการผสมคุณสมบัติเป็นจินตนาการ ไม่ใช่ข้อยืนยันทางวิทยาศาสตร์</p><h3>ความรู้ที่เปิดแล้ว</h3>{DATA.innovations.map(i=><p key={i.id}>{known.has(i.id)?'✓':'○'} {innovations[i.id]}</p>)}{s.scope==='journey'&&s.era==='stone'&&<><h3>เส้นทางสู่ยุคสำริด</h3>{requirements.map((r,i)=><p key={i}>{r.met?'✓':'○'} {['ควบคุมไฟ','สร้างเครื่องมือ','สร้างเครื่องปั้นดินเผา','ค้นพบสิ่งใหม่ 12 ชิ้น'][i]}</p>)}<button disabled={!requirements.every(r=>r.met)} onClick={s.advance}>เปิดยุคสำริด</button></>}<small>v0.5.0 · เสียงสังเคราะห์ต้นฉบับ · ฟอนต์ Itim</small></Sheet></nav></header>
 <main className="game-main"><section className="world-panel"><CivilizationView cards={cards} era={s.era} event={s.event} mode={s.mode}/>{notice&&<div key={notice.id} className={'discovery-toast '+(notice.level?'level-up':'')} role="status"><Icons.Sparkles size={22}/>{notice.text}</div>}<div className="world-caption"><span>{cards.filter(c=>c.depth>0).length} สิ่งที่ค้นพบ</span><span>{s.mode==='sandbox'?'สำรวจอิสระ':`รอบ ${s.round}/3`}</span></div></section>
 <section className="craft-panel" aria-label="การ์ดและโต๊ะทดลอง"><div className="collection-toolbar"><h1>คลังไอเดีย <small>{cards.length}</small></h1><div><Sheet title="สมุดการค้นพบ" trigger={<button className="icon-button" aria-label="สมุดการค้นพบ"><Icons.BookOpen size={19}/></button>}><p>แตะสูตรเพื่อเลือกวัสดุ วัตถุดิบต้องมีในรอบที่เล่น</p>{s.journal.length===0?<p>สูตรแรกของคุณจะปรากฏที่นี่</p>:s.journal.slice(0,100).map((e,i)=><button className="journal-entry" key={i} onClick={()=>s.loadPair([e.aId,e.bId])}><strong>{cardName(e.result.card)}</strong><small>{[e.aId,e.bId].map(id=>byId.get(id)).map((c,i)=>c?cardName(c):[e.a,e.b][i]).join(' + ')}</small></button>)}{s.journal.length>100&&<p>แสดง 100 สูตรล่าสุด</p>}</Sheet><Sheet title="ห้องวิจัย" trigger={<button className="icon-button" aria-label="เปิดห้องวิจัย"><Icons.FlaskConical size={19}/></button>}><ResearchPanel/><p role="status">{feedbackText(s.message)}</p></Sheet><button className="icon-button hint-button" onClick={suggest} aria-label="ใบ้สูตรใหม่"><Icons.Lightbulb size={19}/></button></div></div>
 <div className="search-row"><label className="search"><Icons.Search size={17}/><input aria-label="ค้นหาการ์ด" placeholder="ค้นหาไอเดียหรือคุณสมบัติ…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label="ล้างคำค้น" onClick={()=>setQuery('')}><Icons.X size={16}/></button>}</label><Sheet title="กรองคลังไอเดีย" trigger={<button className="icon-button" aria-label="ตัวกรองเพิ่มเติม"><Icons.SlidersHorizontal size={18}/>{[tag,eraFilter,tier].some(x=>x!=='all')&&<i/>}</button>}><label>คุณสมบัติ<select value={tag} onChange={e=>setTag(e.target.value)}><option value="all">ทั้งหมด</option>{[...new Set(cards.flatMap(c=>c.tags))].sort().map(t=><option key={t} value={t}>{tagNames[t]??t}</option>)}</select></label><label>ยุค<select value={eraFilter} onChange={e=>setEraFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="stone">ยุคหิน</option><option value="bronze">ยุคสำริด</option></select></label><label>ระดับ<select value={tier} onChange={e=>setTier(e.target.value)}><option value="all">ทั้งหมด</option>{[0,1,2,3,4,5].map(t=><option key={t} value={t}>{t===0?'วัสดุเริ่มต้น':`ระดับ ${t}`}</option>)}</select></label><label>เรียงตาม<select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">ใหม่ล่าสุด</option><option value="name">ชื่อ</option><option value="points">แต้มมากที่สุด</option></select></label><button onClick={resetFilters}>ล้างตัวกรอง</button></Sheet></div>
 <div className="filters">{[['all','ทั้งหมด'],['base','วัสดุ'],['new','สร้างแล้ว'],['inventions','สิ่งประดิษฐ์'],['favorites','★ ปักหมุด'],['partners','✦ คู่ใหม่']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 {hint&&<div className="hint" role="status"><span>{hint}</span><button className="icon-button" onClick={()=>setHint('')} aria-label="ปิดคำใบ้"><Icons.X size={14}/></button></div>}
 <div className="deck-scroll"><div className="cards-grid">{visible.map(c=><Tile key={c.id} card={c} onPick={pick} visual={visual} highlight={partners.has(c.id)} favorite={s.favorites.includes(c.id)} onFavorite={s.toggleFavorite}/>)}</div>{!shown.length&&<div className="empty-list"><p>{filter==='partners'&&!anchor?'เลือกวัสดุแรกก่อน แล้วเราจะช่วยไฮไลต์คู่ใหม่':'ยังไม่พบการ์ดที่ตรงกับตัวกรอง'}</p><button onClick={resetFilters}>ดูทั้งหมด</button></div>}{pages>1&&<div className="pagination"><button disabled={!current} onClick={()=>setPage(current-1)} aria-label="หน้าก่อน"><Icons.ChevronLeft/></button><span>{current+1} / {pages}</span><button disabled={current>=pages-1} onClick={()=>setPage(current+1)} aria-label="หน้าถัดไป"><Icons.ChevronRight/></button></div>}<p className="collection-tip">แตะเพื่อเลือก · ลากที่จุดจับ · วัสดุใช้ซ้ำได้</p></div>
 <div className="bench"><div className="bench-label"><span>{anchor?`✦ มี ${partners.size} คู่ใหม่ให้ลอง`:'ลองเริ่มด้วย หิน + หิน'}</span><button className="icon-button" onClick={s.clear} aria-label="ล้างโต๊ะทดลอง"><Icons.RotateCcw size={16}/></button></div><div className="bench-row">{s.slots.map((c,i)=><button key={i} data-ingredient-slot={i} className={'ingredient '+(c?.tone??'')} aria-label={c?`นำ ${cardName(c)} ออกจากช่อง ${i+1}`:`ช่องวัสดุ ${i+1}`} onClick={()=>{if(c){const slots=[...s.slots];slots[i]=null;useGame.setState({slots});}else setHint('แตะการ์ดในคลังเพื่อเลือก หรือวางการ์ดลงช่องนี้');}}><small>{i===0?'วัสดุแรก':'ผสมกับ'}</small><strong>{c?cardName(c):'+ เลือกการ์ด'}</strong></button>)}<button className="combine-button" disabled={!s.slots.every(Boolean)||s.mode==='challenge'&&s.done} onClick={s.craft}><Icons.Sparkles size={20}/><span>ทดลอง!</span></button></div><p className="reaction" role="status">{feedbackText(s.message)}</p></div>
 </section></main>
 <Dialog.Root open={s.done&&s.mode==='challenge'}><Dialog.Portal><Dialog.Overlay className="sheet-overlay"/><Dialog.Content className="sheet round-sheet"><Dialog.Title>{s.round===3?'จบการสำรวจแล้ว!':'พักแล้วไปต่อกัน'}</Dialog.Title><Dialog.Description>{s.score} แต้ม · ค้นพบ {s.discovered.length} สิ่ง</Dialog.Description><button className="combine-button" onClick={()=>s.round<3?s.next():s.start('challenge')}>{s.round<3?'เริ่มรอบถัดไป':'เล่นอีกครั้ง'}</button><button onClick={()=>s.start('sandbox')}>กลับไปสำรวจอิสระ</button></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
